"""Add department_id and course_id fields to admission_students

Revision ID: 011d614e2802
Revises: f18b4d43ac77
Create Date: 2026-01-30 06:50:56.139357

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '011d614e2802'
down_revision: Union[str, Sequence[str], None] = 'f18b4d43ac77'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admission_students', sa.Column('department_id', sa.UUID(), nullable=True))
    op.add_column('admission_students', sa.Column('course_id', sa.UUID(), nullable=True))
    op.alter_column('admission_students', 'institution_id',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.UUID(),
               existing_nullable=True,
               postgresql_using='institution_id::uuid')
    op.create_index(op.f('ix_admission_students_course_id'), 'admission_students', ['course_id'], unique=False)
    op.create_index(op.f('ix_admission_students_department_id'), 'admission_students', ['department_id'], unique=False)
    op.create_index(op.f('ix_admission_students_institution_id'), 'admission_students', ['institution_id'], unique=False)
    op.create_foreign_key(None, 'admission_students', 'institutions', ['institution_id'], ['id'])
    op.create_foreign_key(None, 'admission_students', 'courses', ['course_id'], ['id'])
    op.create_foreign_key(None, 'admission_students', 'departments', ['department_id'], ['id'])
    op.drop_column('admission_students', 'department')
    op.drop_column('admission_students', 'course')
    op.alter_column('application_transactions', 'amount',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=2),
               existing_nullable=False)
    op.alter_column('invoice_line_items', 'amount',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=2),
               existing_nullable=False)
    op.alter_column('invoice_line_items', 'discount_amount',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=2),
               existing_nullable=True)
    op.alter_column('invoice_line_items', 'tax_amount',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=2),
               existing_nullable=True)
    op.alter_column('invoice_line_items', 'net_amount',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=2),
               existing_nullable=False)
    op.alter_column('invoices', 'amount',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=2),
               existing_nullable=False)
    op.alter_column('invoices', 'paid_amount',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=2),
               existing_nullable=False)
    op.alter_column('invoices', 'balance_due',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=2),
               existing_nullable=False)
    op.alter_column('payments', 'amount',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=2),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('payments', 'amount',
               existing_type=sa.Float(precision=2),
               type_=sa.REAL(),
               existing_nullable=False)
    op.alter_column('invoices', 'balance_due',
               existing_type=sa.Float(precision=2),
               type_=sa.REAL(),
               existing_nullable=False)
    op.alter_column('invoices', 'paid_amount',
               existing_type=sa.Float(precision=2),
               type_=sa.REAL(),
               existing_nullable=False)
    op.alter_column('invoices', 'amount',
               existing_type=sa.Float(precision=2),
               type_=sa.REAL(),
               existing_nullable=False)
    op.alter_column('invoice_line_items', 'net_amount',
               existing_type=sa.Float(precision=2),
               type_=sa.REAL(),
               existing_nullable=False)
    op.alter_column('invoice_line_items', 'tax_amount',
               existing_type=sa.Float(precision=2),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('invoice_line_items', 'discount_amount',
               existing_type=sa.Float(precision=2),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('invoice_line_items', 'amount',
               existing_type=sa.Float(precision=2),
               type_=sa.REAL(),
               existing_nullable=False)
    op.alter_column('application_transactions', 'amount',
               existing_type=sa.Float(precision=2),
               type_=sa.REAL(),
               existing_nullable=False)
    op.add_column('admission_students', sa.Column('course', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    op.add_column('admission_students', sa.Column('department', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'admission_students', type_='foreignkey')
    op.drop_constraint(None, 'admission_students', type_='foreignkey')
    op.drop_constraint(None, 'admission_students', type_='foreignkey')
    op.drop_index(op.f('ix_admission_students_institution_id'), table_name='admission_students')
    op.drop_index(op.f('ix_admission_students_department_id'), table_name='admission_students')
    op.drop_index(op.f('ix_admission_students_course_id'), table_name='admission_students')
    op.alter_column('admission_students', 'institution_id',
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.drop_column('admission_students', 'course_id')
    op.drop_column('admission_students', 'department_id')
    # ### end Alembic commands ###
