"""add vehicle_charge to material_in

Revision ID: 0d429be0c15f
Revises: 44665c0b4e03
Create Date: 2026-05-11 10:25:50.099612

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d429be0c15f'
down_revision: Union[str, Sequence[str], None] = '44665c0b4e03'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('material_in_entries', sa.Column('vehicle_charge', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('material_in_entries', 'vehicle_charge')
    # ### end Alembic commands ###
