"""rename vehicle_charge to vehicle_name

Revision ID: 263a63458153
Revises: fdae42e21cd8
Create Date: 2026-05-11 08:22:11.174511

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '263a63458153'
down_revision: Union[str, Sequence[str], None] = 'fdae42e21cd8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_gate_material_entries_deleted_at'), table_name='gate_material_entries')
    op.drop_table('gate_material_entries')
    op.drop_index(op.f('ix_sis_student_profiles_admission_student_id'), table_name='sis_student_profiles')
    op.drop_index(op.f('ix_sis_student_profiles_deleted_at'), table_name='sis_student_profiles')
    op.drop_index(op.f('ix_sis_student_profiles_register_number'), table_name='sis_student_profiles')
    op.drop_table('sis_student_profiles')
    op.drop_index(op.f('ix_scrap_materials_deleted_at'), table_name='scrap_materials')
    op.drop_index(op.f('ix_scrap_materials_pass_number'), table_name='scrap_materials')
    op.drop_table('scrap_materials')
    op.add_column('material_in_entries', sa.Column('vehicle_name', sa.String(length=100), nullable=True))
    op.drop_column('material_in_entries', 'vehicle_charge')
    op.add_column('material_passes', sa.Column('vehicle_name', sa.String(length=100), nullable=True))
    op.drop_column('material_passes', 'vehicle_charge')
    op.alter_column('visitors', 'person_type_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_constraint(op.f('visitors_person_type_id_fkey'), 'visitors', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(op.f('visitors_person_type_id_fkey'), 'visitors', 'person_types', ['person_type_id'], ['id'])
    op.alter_column('visitors', 'person_type_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.add_column('material_passes', sa.Column('vehicle_charge', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.drop_column('material_passes', 'vehicle_name')
    op.add_column('material_in_entries', sa.Column('vehicle_charge', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.drop_column('material_in_entries', 'vehicle_name')
    op.create_table('scrap_materials',
    sa.Column('pass_number', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('department', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('material_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('company_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('place', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('deleted_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('scrap_materials_created_by_fkey'), initially='DEFERRED', deferrable=True),
    sa.ForeignKeyConstraint(['deleted_by'], ['users.id'], name=op.f('scrap_materials_deleted_by_fkey'), initially='DEFERRED', deferrable=True),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f('scrap_materials_updated_by_fkey'), initially='DEFERRED', deferrable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('scrap_materials_pkey'))
    )
    op.create_index(op.f('ix_scrap_materials_pass_number'), 'scrap_materials', ['pass_number'], unique=True)
    op.create_index(op.f('ix_scrap_materials_deleted_at'), 'scrap_materials', ['deleted_at'], unique=False)
    op.create_table('sis_student_profiles',
    sa.Column('admission_student_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('blood_group', postgresql.ENUM('A_POS', 'A_NEG', 'B_POS', 'B_NEG', 'AB_POS', 'AB_NEG', 'O_POS', 'O_NEG', name='bloodgroupenum'), autoincrement=False, nullable=True),
    sa.Column('nationality', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('mother_tongue', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('whatsapp_number', sa.VARCHAR(length=15), autoincrement=False, nullable=True),
    sa.Column('differently_abled', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('differently_abled_type', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('ex_serviceman_child', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('first_generation_graduate', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('mother_name', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('mother_occupation', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('father_occupation', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('guardian_name', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('guardian_relation', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('guardian_mobile', sa.VARCHAR(length=15), autoincrement=False, nullable=True),
    sa.Column('register_number', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('hostel_status', postgresql.ENUM('DAY_SCHOLAR', 'HOSTELLER', 'DAY_BOARDER', name='hostelstatusenum'), autoincrement=False, nullable=True),
    sa.Column('photo_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('profile_completed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('profile_completed_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('deleted_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['admission_student_id'], ['admission_students.id'], name=op.f('sis_student_profiles_admission_student_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('sis_student_profiles_created_by_fkey'), initially='DEFERRED', deferrable=True),
    sa.ForeignKeyConstraint(['deleted_by'], ['users.id'], name=op.f('sis_student_profiles_deleted_by_fkey'), initially='DEFERRED', deferrable=True),
    sa.ForeignKeyConstraint(['profile_completed_by'], ['users.id'], name=op.f('sis_student_profiles_profile_completed_by_fkey'), initially='DEFERRED', deferrable=True),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f('sis_student_profiles_updated_by_fkey'), initially='DEFERRED', deferrable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('sis_student_profiles_pkey'))
    )
    op.create_index(op.f('ix_sis_student_profiles_register_number'), 'sis_student_profiles', ['register_number'], unique=False)
    op.create_index(op.f('ix_sis_student_profiles_deleted_at'), 'sis_student_profiles', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_sis_student_profiles_admission_student_id'), 'sis_student_profiles', ['admission_student_id'], unique=True)
    op.create_table('gate_material_entries',
    sa.Column('pass_no', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('company_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('material_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('out_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('out_time', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('in_qty', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('pending_quantity', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('place', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('vehicle_number', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('vehicle_charge', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=8), autoincrement=False, nullable=False),
    sa.Column('entry_type', sa.VARCHAR(length=12), autoincrement=False, nullable=False),
    sa.Column('in_time', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('deleted_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('gate_material_entries_created_by_fkey'), initially='DEFERRED', deferrable=True),
    sa.ForeignKeyConstraint(['deleted_by'], ['users.id'], name=op.f('gate_material_entries_deleted_by_fkey'), initially='DEFERRED', deferrable=True),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f('gate_material_entries_updated_by_fkey'), initially='DEFERRED', deferrable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('gate_material_entries_pkey')),
    sa.UniqueConstraint('pass_no', name=op.f('gate_material_entries_pass_no_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_gate_material_entries_deleted_at'), 'gate_material_entries', ['deleted_at'], unique=False)
    # ### end Alembic commands ###
