"""add_student_deposit_model

Revision ID: 2ad28a0a3bf9
Revises: 8d5468ceb984
Create Date: 2026-03-08 16:12:48.629575

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2ad28a0a3bf9'
down_revision: Union[str, Sequence[str], None] = '8d5468ceb984'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('consultancy_references', 'reference_staff_1',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.drop_constraint(op.f('fee_structure_items_fee_sub_head_id_fkey'), 'fee_structure_items', type_='foreignkey')
    op.create_foreign_key(None, 'fee_structure_items', 'fee_sub_heads', ['fee_sub_head_id'], ['id'], ondelete='SET NULL')
    op.create_index(op.f('ix_hsc_subject_marks_deleted_at'), 'hsc_subject_marks', ['deleted_at'], unique=False)
    op.create_foreign_key(None, 'hsc_subject_marks', 'users', ['updated_by'], ['id'], initially='DEFERRED', deferrable=True, use_alter=True)
    op.create_foreign_key(None, 'hsc_subject_marks', 'users', ['created_by'], ['id'], initially='DEFERRED', deferrable=True, use_alter=True)
    op.create_foreign_key(None, 'hsc_subject_marks', 'users', ['deleted_by'], ['id'], initially='DEFERRED', deferrable=True, use_alter=True)
    op.alter_column('school_list_uploads', 'record_count',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('school_list_uploads', 'upload_status',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text("'completed'::character varying"))
    op.create_index(op.f('ix_school_list_uploads_deleted_at'), 'school_list_uploads', ['deleted_at'], unique=False)
    op.create_foreign_key(None, 'school_list_uploads', 'users', ['deleted_by'], ['id'], initially='DEFERRED', deferrable=True, use_alter=True)
    op.create_foreign_key(None, 'school_list_uploads', 'users', ['updated_by'], ['id'], initially='DEFERRED', deferrable=True, use_alter=True)
    op.create_foreign_key(None, 'school_list_uploads', 'users', ['created_by'], ['id'], initially='DEFERRED', deferrable=True, use_alter=True)
    op.alter_column('school_master', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.create_index(op.f('ix_school_master_deleted_at'), 'school_master', ['deleted_at'], unique=False)
    op.create_foreign_key(None, 'school_master', 'users', ['deleted_by'], ['id'], initially='DEFERRED', deferrable=True, use_alter=True)
    op.create_foreign_key(None, 'school_master', 'users', ['created_by'], ['id'], initially='DEFERRED', deferrable=True, use_alter=True)
    op.create_foreign_key(None, 'school_master', 'users', ['updated_by'], ['id'], initially='DEFERRED', deferrable=True, use_alter=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'school_master', type_='foreignkey')
    op.drop_constraint(None, 'school_master', type_='foreignkey')
    op.drop_constraint(None, 'school_master', type_='foreignkey')
    op.drop_index(op.f('ix_school_master_deleted_at'), table_name='school_master')
    op.alter_column('school_master', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.drop_constraint(None, 'school_list_uploads', type_='foreignkey')
    op.drop_constraint(None, 'school_list_uploads', type_='foreignkey')
    op.drop_constraint(None, 'school_list_uploads', type_='foreignkey')
    op.drop_index(op.f('ix_school_list_uploads_deleted_at'), table_name='school_list_uploads')
    op.alter_column('school_list_uploads', 'upload_status',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               existing_server_default=sa.text("'completed'::character varying"))
    op.alter_column('school_list_uploads', 'record_count',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.drop_constraint(None, 'hsc_subject_marks', type_='foreignkey')
    op.drop_constraint(None, 'hsc_subject_marks', type_='foreignkey')
    op.drop_constraint(None, 'hsc_subject_marks', type_='foreignkey')
    op.drop_index(op.f('ix_hsc_subject_marks_deleted_at'), table_name='hsc_subject_marks')
    op.drop_constraint(None, 'fee_structure_items', type_='foreignkey')
    op.create_foreign_key(op.f('fee_structure_items_fee_sub_head_id_fkey'), 'fee_structure_items', 'fee_sub_heads', ['fee_sub_head_id'], ['id'], ondelete='CASCADE')
    op.alter_column('consultancy_references', 'reference_staff_1',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    # ### end Alembic commands ###
