"""add_source_column_to_admission_students

Revision ID: 4ac8ad16ca1a
Revises: b5fe635d4eee
Create Date: 2026-04-17 15:37:59.512147

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ac8ad16ca1a'
down_revision: Union[str, Sequence[str], None] = 'b5fe635d4eee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admission_students', sa.Column('source', sa.Enum('GATE_ENQUIRY', 'DIRECT_ENTRY', 'COUNSELING', name='sourceenum'), server_default='GATE_ENQUIRY', nullable=False))
    op.add_column('admission_students', sa.Column('is_lateral_entry', sa.Boolean(), server_default=sa.false(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('admission_students', 'is_lateral_entry')
    op.drop_column('admission_students', 'source')
    # ### end Alembic commands ###
