"""

Revision ID: 5bdc9b1a70e3
Revises: 20260222_postadm_fields
Create Date: 2026-02-22 10:56:57.130842

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5bdc9b1a70e3'
down_revision: Union[str, Sequence[str], None] = '20260222_postadm_fields'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def _table_columns(inspector, table_name: str) -> set[str]:
    try:
        return {col["name"] for col in inspector.get_columns(table_name)}
    except Exception:
        return set()


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ux_academic_years_admission_active_per_institution'), table_name='academic_years', postgresql_where='(admission_active IS TRUE)')
    op.drop_index(op.f('ux_academic_years_status_active_per_institution'), table_name='academic_years', postgresql_where='(status IS TRUE)')
    op.alter_column('application_transactions', 'amount',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=2),
               existing_nullable=False)
    op.create_foreign_key(None, 'department_change_requests', 'users', ['deleted_by'], ['id'], initially='DEFERRED', deferrable=True, use_alter=True)
    op.create_foreign_key(None, 'department_change_requests', 'users', ['updated_by'], ['id'], initially='DEFERRED', deferrable=True, use_alter=True)
    op.create_foreign_key(None, 'department_change_requests', 'users', ['created_by'], ['id'], initially='DEFERRED', deferrable=True, use_alter=True)
    # Add as nullable first, then backfill existing rows before enforcing NOT NULL.
    op.add_column('financial_years', sa.Column('institution_id', sa.UUID(), nullable=True))

    bind = op.get_bind()
    inspector = sa.inspect(bind)
    fy_cols = _table_columns(inspector, "financial_years")

    # Backfill from academic_years if financial_years.academic_year_id exists.
    if {"institution_id", "academic_year_id"}.issubset(fy_cols):
        op.execute(
            """
            UPDATE financial_years fy
            SET institution_id = ay.institution_id
            FROM academic_years ay
            WHERE fy.academic_year_id = ay.id
              AND fy.institution_id IS NULL;
            """
        )

    # Fill remaining NULLs with the first available institution to keep migration forward-compatible
    # on legacy databases with existing financial_year rows.
    op.execute(
        """
        UPDATE financial_years
        SET institution_id = (
            SELECT id FROM institutions ORDER BY created_at NULLS LAST, id LIMIT 1
        )
        WHERE institution_id IS NULL;
        """
    )

    op.create_index(op.f('ix_financial_years_institution_id'), 'financial_years', ['institution_id'], unique=False)
    op.create_foreign_key(None, 'financial_years', 'institutions', ['institution_id'], ['id'], ondelete='CASCADE')

    # Enforce NOT NULL only when there are no NULLs left.
    remaining_nulls = bind.execute(sa.text("SELECT COUNT(*) FROM financial_years WHERE institution_id IS NULL")).scalar() or 0
    if remaining_nulls == 0:
        op.alter_column('financial_years', 'institution_id', nullable=False)

    op.alter_column('invoice_line_items', 'amount',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=2),
               existing_nullable=False)
    op.alter_column('invoice_line_items', 'discount_amount',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=2),
               existing_nullable=True)
    op.alter_column('invoice_line_items', 'tax_amount',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=2),
               existing_nullable=True)
    op.alter_column('invoice_line_items', 'net_amount',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=2),
               existing_nullable=False)
    op.alter_column('invoices', 'amount',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=2),
               existing_nullable=False)
    op.alter_column('invoices', 'paid_amount',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=2),
               existing_nullable=False)
    op.alter_column('invoices', 'balance_due',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=2),
               existing_nullable=False)
    op.alter_column('payments', 'amount',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=2),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('payments', 'amount',
               existing_type=sa.Float(precision=2),
               type_=sa.REAL(),
               existing_nullable=False)
    op.alter_column('invoices', 'balance_due',
               existing_type=sa.Float(precision=2),
               type_=sa.REAL(),
               existing_nullable=False)
    op.alter_column('invoices', 'paid_amount',
               existing_type=sa.Float(precision=2),
               type_=sa.REAL(),
               existing_nullable=False)
    op.alter_column('invoices', 'amount',
               existing_type=sa.Float(precision=2),
               type_=sa.REAL(),
               existing_nullable=False)
    op.alter_column('invoice_line_items', 'net_amount',
               existing_type=sa.Float(precision=2),
               type_=sa.REAL(),
               existing_nullable=False)
    op.alter_column('invoice_line_items', 'tax_amount',
               existing_type=sa.Float(precision=2),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('invoice_line_items', 'discount_amount',
               existing_type=sa.Float(precision=2),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('invoice_line_items', 'amount',
               existing_type=sa.Float(precision=2),
               type_=sa.REAL(),
               existing_nullable=False)
    op.drop_constraint(None, 'financial_years', type_='foreignkey')
    op.drop_index(op.f('ix_financial_years_institution_id'), table_name='financial_years')
    op.drop_column('financial_years', 'institution_id')
    op.drop_constraint(None, 'department_change_requests', type_='foreignkey')
    op.drop_constraint(None, 'department_change_requests', type_='foreignkey')
    op.drop_constraint(None, 'department_change_requests', type_='foreignkey')
    op.alter_column('application_transactions', 'amount',
               existing_type=sa.Float(precision=2),
               type_=sa.REAL(),
               existing_nullable=False)
    op.create_index(op.f('ux_academic_years_status_active_per_institution'), 'academic_years', ['institution_id'], unique=True, postgresql_where='(status IS TRUE)')
    op.create_index(op.f('ux_academic_years_admission_active_per_institution'), 'academic_years', ['institution_id'], unique=True, postgresql_where='(admission_active IS TRUE)')
    # ### end Alembic commands ###
