"""Add admission_quota_id and documents_submitted

Revision ID: 70f5bbadcf97
Revises: 6e6c02dbf26b
Create Date: 2026-02-11 15:37:51.706848

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '70f5bbadcf97'
down_revision: Union[str, Sequence[str], None] = '6e6c02dbf26b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fee_structures_quota_id_fkey'), 'fee_structures', type_='foreignkey')
    op.drop_index(op.f('ix_quotas_code'), table_name='quotas')
    op.drop_index(op.f('ix_quotas_institution_id'), table_name='quotas')
    op.drop_table('quotas')
    op.drop_index(op.f('ix_academic_year_courses_academic_year_id'), table_name='academic_year_courses')
    op.drop_index(op.f('ix_academic_year_courses_course_id'), table_name='academic_year_courses')
    op.drop_constraint(op.f('academic_year_courses_academic_year_id_fkey'), 'academic_year_courses', type_='foreignkey')
    op.drop_constraint(op.f('academic_year_courses_course_id_fkey'), 'academic_year_courses', type_='foreignkey')
    op.create_foreign_key(None, 'academic_year_courses', 'academic_years', ['academic_year_id'], ['id'])
    op.create_foreign_key(None, 'academic_year_courses', 'courses', ['course_id'], ['id'])
    op.drop_constraint(op.f('academic_years_year_name_key'), 'academic_years', type_='unique')
    op.drop_constraint(op.f('academic_years_institution_id_fkey'), 'academic_years', type_='foreignkey')
    op.create_foreign_key(None, 'academic_years', 'institutions', ['institution_id'], ['id'])
    op.add_column('admission_students', sa.Column('admission_quota_id', sa.UUID(), nullable=True))
    op.add_column('admission_students', sa.Column('admission_type_id', sa.UUID(), nullable=True))
    op.add_column('admission_students', sa.Column('documents_submitted', sa.JSON(), nullable=True))
    op.create_index(op.f('ix_admission_students_admission_quota_id'), 'admission_students', ['admission_quota_id'], unique=False)
    op.create_index(op.f('ix_admission_students_admission_type_id'), 'admission_students', ['admission_type_id'], unique=False)
    op.create_foreign_key(None, 'admission_students', 'seat_quotas', ['admission_quota_id'], ['id'])
    op.create_foreign_key(None, 'admission_students', 'admission_types', ['admission_type_id'], ['id'])
    op.drop_column('admission_students', 'admission_quota')
    op.drop_column('admission_students', 'admission_type')
    op.alter_column('admission_types', 'code',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('admission_types', 'description',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=500),
               existing_nullable=True)
    op.alter_column('admission_types', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('admission_types', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('admission_types', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(op.f('admission_types_name_key'), 'admission_types', type_='unique')
    op.drop_index(op.f('ix_admission_types_code'), table_name='admission_types')
    op.drop_index(op.f('ix_admission_types_institution_id'), table_name='admission_types')
    op.create_index(op.f('ix_admission_types_name'), 'admission_types', ['name'], unique=True)
    op.create_unique_constraint(None, 'admission_types', ['code'])
    op.drop_constraint(op.f('admission_types_institution_id_fkey'), 'admission_types', type_='foreignkey')
    op.drop_column('admission_types', 'institution_id')
    op.alter_column('application_transactions', 'amount',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=2),
               existing_nullable=False)
    op.create_foreign_key(None, 'fee_structures', 'seat_quotas', ['quota_id'], ['id'], ondelete='SET NULL')
    op.alter_column('invoice_line_items', 'amount',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=2),
               existing_nullable=False)
    op.alter_column('invoice_line_items', 'discount_amount',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=2),
               existing_nullable=True)
    op.alter_column('invoice_line_items', 'tax_amount',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=2),
               existing_nullable=True)
    op.alter_column('invoice_line_items', 'net_amount',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=2),
               existing_nullable=False)
    op.alter_column('invoices', 'amount',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=2),
               existing_nullable=False)
    op.alter_column('invoices', 'paid_amount',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=2),
               existing_nullable=False)
    op.alter_column('invoices', 'balance_due',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=2),
               existing_nullable=False)
    op.alter_column('payments', 'amount',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=2),
               existing_nullable=False)
    op.drop_constraint(op.f('semester_periods_academic_year_id_fkey'), 'semester_periods', type_='foreignkey')
    op.create_foreign_key(None, 'semester_periods', 'academic_years', ['academic_year_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'semester_periods', type_='foreignkey')
    op.create_foreign_key(op.f('semester_periods_academic_year_id_fkey'), 'semester_periods', 'academic_years', ['academic_year_id'], ['id'], ondelete='CASCADE')
    op.alter_column('payments', 'amount',
               existing_type=sa.Float(precision=2),
               type_=sa.REAL(),
               existing_nullable=False)
    op.alter_column('invoices', 'balance_due',
               existing_type=sa.Float(precision=2),
               type_=sa.REAL(),
               existing_nullable=False)
    op.alter_column('invoices', 'paid_amount',
               existing_type=sa.Float(precision=2),
               type_=sa.REAL(),
               existing_nullable=False)
    op.alter_column('invoices', 'amount',
               existing_type=sa.Float(precision=2),
               type_=sa.REAL(),
               existing_nullable=False)
    op.alter_column('invoice_line_items', 'net_amount',
               existing_type=sa.Float(precision=2),
               type_=sa.REAL(),
               existing_nullable=False)
    op.alter_column('invoice_line_items', 'tax_amount',
               existing_type=sa.Float(precision=2),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('invoice_line_items', 'discount_amount',
               existing_type=sa.Float(precision=2),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('invoice_line_items', 'amount',
               existing_type=sa.Float(precision=2),
               type_=sa.REAL(),
               existing_nullable=False)
    op.drop_constraint(None, 'fee_structures', type_='foreignkey')
    op.create_foreign_key(op.f('fee_structures_quota_id_fkey'), 'fee_structures', 'quotas', ['quota_id'], ['id'], ondelete='SET NULL')
    op.alter_column('application_transactions', 'amount',
               existing_type=sa.Float(precision=2),
               type_=sa.REAL(),
               existing_nullable=False)
    op.add_column('admission_types', sa.Column('institution_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('admission_types_institution_id_fkey'), 'admission_types', 'institutions', ['institution_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'admission_types', type_='unique')
    op.drop_index(op.f('ix_admission_types_name'), table_name='admission_types')
    op.create_index(op.f('ix_admission_types_institution_id'), 'admission_types', ['institution_id'], unique=False)
    op.create_index(op.f('ix_admission_types_code'), 'admission_types', ['code'], unique=True)
    op.create_unique_constraint(op.f('admission_types_name_key'), 'admission_types', ['name'], postgresql_nulls_not_distinct=False)
    op.alter_column('admission_types', 'updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('admission_types', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('admission_types', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('admission_types', 'description',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('admission_types', 'code',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.add_column('admission_students', sa.Column('admission_type', postgresql.ENUM('GENERAL', 'LATERAL', 'TRANSFER', 'DIRECT', 'MANAGEMENT', 'COUNSELING', name='admissiontypeenum'), autoincrement=False, nullable=True))
    op.add_column('admission_students', sa.Column('admission_quota', postgresql.ENUM('MANAGEMENT', 'GOVERNMENT', name='admissionquotaenum'), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'admission_students', type_='foreignkey')
    op.drop_constraint(None, 'admission_students', type_='foreignkey')
    op.drop_index(op.f('ix_admission_students_admission_type_id'), table_name='admission_students')
    op.drop_index(op.f('ix_admission_students_admission_quota_id'), table_name='admission_students')
    op.drop_column('admission_students', 'documents_submitted')
    op.drop_column('admission_students', 'admission_type_id')
    op.drop_column('admission_students', 'admission_quota_id')
    op.drop_constraint(None, 'academic_years', type_='foreignkey')
    op.create_foreign_key(op.f('academic_years_institution_id_fkey'), 'academic_years', 'institutions', ['institution_id'], ['id'], ondelete='CASCADE')
    op.create_unique_constraint(op.f('academic_years_year_name_key'), 'academic_years', ['year_name'], postgresql_nulls_not_distinct=False)
    op.drop_constraint(None, 'academic_year_courses', type_='foreignkey')
    op.drop_constraint(None, 'academic_year_courses', type_='foreignkey')
    op.create_foreign_key(op.f('academic_year_courses_course_id_fkey'), 'academic_year_courses', 'courses', ['course_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('academic_year_courses_academic_year_id_fkey'), 'academic_year_courses', 'academic_years', ['academic_year_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_academic_year_courses_course_id'), 'academic_year_courses', ['course_id'], unique=False)
    op.create_index(op.f('ix_academic_year_courses_academic_year_id'), 'academic_year_courses', ['academic_year_id'], unique=False)
    op.create_table('quotas',
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('code', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('institution_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('deleted_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('quotas_created_by_fkey'), initially='DEFERRED', deferrable=True),
    sa.ForeignKeyConstraint(['deleted_by'], ['users.id'], name=op.f('quotas_deleted_by_fkey'), initially='DEFERRED', deferrable=True),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], name=op.f('quotas_institution_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f('quotas_updated_by_fkey'), initially='DEFERRED', deferrable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('quotas_pkey')),
    sa.UniqueConstraint('name', name=op.f('quotas_name_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_quotas_institution_id'), 'quotas', ['institution_id'], unique=False)
    op.create_index(op.f('ix_quotas_code'), 'quotas', ['code'], unique=True)
    # ### end Alembic commands ###
