"""

Revision ID: 7e89b05a74dc
Revises: 48bd79f2a316
Create Date: 2026-01-19 06:50:33.184904

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7e89b05a74dc'
down_revision: Union[str, Sequence[str], None] = '48bd79f2a316'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'academic_year_departments', 'users', ['updated_by'], ['id'], initially='DEFERRED', deferrable=True, use_alter=True)
    op.create_foreign_key(None, 'academic_year_departments', 'users', ['deleted_by'], ['id'], initially='DEFERRED', deferrable=True, use_alter=True)
    op.create_foreign_key(None, 'academic_year_departments', 'users', ['created_by'], ['id'], initially='DEFERRED', deferrable=True, use_alter=True)
    op.drop_column('admission_visitors', 'visit_status')
    op.drop_column('admission_visitors', 'check_out_time')
    op.drop_column('admission_visitors', 'check_in_time')
    op.alter_column('application_transactions', 'amount',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=2),
               existing_nullable=False)
    op.drop_constraint(op.f('application_transactions_deleted_by_fkey'), 'application_transactions', type_='foreignkey')
    op.drop_constraint(op.f('application_transactions_updated_by_fkey'), 'application_transactions', type_='foreignkey')
    op.create_foreign_key(None, 'application_transactions', 'users', ['deleted_by'], ['id'], initially='DEFERRED', deferrable=True, use_alter=True)
    op.create_foreign_key(None, 'application_transactions', 'users', ['updated_by'], ['id'], initially='DEFERRED', deferrable=True, use_alter=True)
    op.execute("DELETE FROM departments WHERE institution_id NOT IN (SELECT id FROM institutions)")
    op.create_foreign_key(None, 'departments', 'institutions', ['institution_id'], ['id'])
    op.create_foreign_key(None, 'diploma_details', 'admission_students', ['student_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_financial_years_academic_year_id'), table_name='financial_years')
    op.drop_index(op.f('ix_financial_years_institution_id'), table_name='financial_years')
    op.drop_constraint(op.f('financial_years_academic_year_id_fkey'), 'financial_years', type_='foreignkey')
    op.drop_constraint(op.f('financial_years_institution_id_fkey'), 'financial_years', type_='foreignkey')
    op.drop_column('financial_years', 'academic_year_id')
    op.drop_column('financial_years', 'institution_id')
    op.create_foreign_key(None, 'hsc_details', 'admission_students', ['student_id'], ['id'], ondelete='CASCADE')
    op.alter_column('invoice_line_items', 'amount',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=2),
               existing_nullable=False)
    op.alter_column('invoice_line_items', 'discount_amount',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=2),
               existing_nullable=True)
    op.alter_column('invoice_line_items', 'tax_amount',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=2),
               existing_nullable=True)
    op.alter_column('invoice_line_items', 'net_amount',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=2),
               existing_nullable=False)
    op.create_foreign_key(None, 'invoice_line_items', 'fee_heads', ['fee_head_id'], ['id'], ondelete='SET NULL')
    op.alter_column('invoices', 'amount',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=2),
               existing_nullable=False)
    op.alter_column('invoices', 'paid_amount',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=2),
               existing_nullable=False)
    op.alter_column('invoices', 'balance_due',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=2),
               existing_nullable=False)
    op.create_foreign_key(None, 'invoices', 'admission_students', ['student_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'invoices', 'institutions', ['institution_id'], ['id'], ondelete='CASCADE')
    op.add_column('payments', sa.Column('cash_counter_id', sa.UUID(), nullable=True))
    op.alter_column('payments', 'amount',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=2),
               existing_nullable=False)
    op.create_foreign_key(None, 'payments', 'cash_counters', ['cash_counter_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'pg_details', 'admission_students', ['student_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'sslc_details', 'admission_students', ['student_id'], ['id'], ondelete='CASCADE')
    op.add_column('visitors', sa.Column('pass_number', sa.String(length=50), nullable=True))
    op.drop_index(op.f('ix_visitors_gate_pass_no'), table_name='visitors')
    op.drop_constraint(op.f('uq_visitors_gate_pass_no'), 'visitors', type_='unique')
    op.create_unique_constraint(None, 'visitors', ['pass_number'])
    op.create_foreign_key(None, 'visitors', 'institutions', ['institution_id'], ['id'])
    op.drop_column('visitors', 'gate_pass_no')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('visitors', sa.Column('gate_pass_no', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'visitors', type_='foreignkey')
    op.drop_constraint(None, 'visitors', type_='unique')
    op.create_unique_constraint(op.f('uq_visitors_gate_pass_no'), 'visitors', ['gate_pass_no'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_visitors_gate_pass_no'), 'visitors', ['gate_pass_no'], unique=False)
    op.drop_column('visitors', 'pass_number')
    op.drop_constraint(None, 'sslc_details', type_='foreignkey')
    op.drop_constraint(None, 'pg_details', type_='foreignkey')
    op.drop_constraint(None, 'payments', type_='foreignkey')
    op.alter_column('payments', 'amount',
               existing_type=sa.Float(precision=2),
               type_=sa.REAL(),
               existing_nullable=False)
    op.drop_column('payments', 'cash_counter_id')
    op.drop_constraint(None, 'invoices', type_='foreignkey')
    op.drop_constraint(None, 'invoices', type_='foreignkey')
    op.alter_column('invoices', 'balance_due',
               existing_type=sa.Float(precision=2),
               type_=sa.REAL(),
               existing_nullable=False)
    op.alter_column('invoices', 'paid_amount',
               existing_type=sa.Float(precision=2),
               type_=sa.REAL(),
               existing_nullable=False)
    op.alter_column('invoices', 'amount',
               existing_type=sa.Float(precision=2),
               type_=sa.REAL(),
               existing_nullable=False)
    op.drop_constraint(None, 'invoice_line_items', type_='foreignkey')
    op.alter_column('invoice_line_items', 'net_amount',
               existing_type=sa.Float(precision=2),
               type_=sa.REAL(),
               existing_nullable=False)
    op.alter_column('invoice_line_items', 'tax_amount',
               existing_type=sa.Float(precision=2),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('invoice_line_items', 'discount_amount',
               existing_type=sa.Float(precision=2),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('invoice_line_items', 'amount',
               existing_type=sa.Float(precision=2),
               type_=sa.REAL(),
               existing_nullable=False)
    op.drop_constraint(None, 'hsc_details', type_='foreignkey')
    op.add_column('financial_years', sa.Column('institution_id', sa.UUID(), autoincrement=False, nullable=False))
    op.add_column('financial_years', sa.Column('academic_year_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('financial_years_institution_id_fkey'), 'financial_years', 'institutions', ['institution_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('financial_years_academic_year_id_fkey'), 'financial_years', 'academic_years', ['academic_year_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_financial_years_institution_id'), 'financial_years', ['institution_id'], unique=False)
    op.create_index(op.f('ix_financial_years_academic_year_id'), 'financial_years', ['academic_year_id'], unique=False)
    op.drop_constraint(None, 'diploma_details', type_='foreignkey')
    op.drop_constraint(None, 'departments', type_='foreignkey')
    op.drop_constraint(None, 'application_transactions', type_='foreignkey')
    op.drop_constraint(None, 'application_transactions', type_='foreignkey')
    op.create_foreign_key(op.f('application_transactions_updated_by_fkey'), 'application_transactions', 'users', ['updated_by'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('application_transactions_deleted_by_fkey'), 'application_transactions', 'users', ['deleted_by'], ['id'], ondelete='SET NULL')
    op.alter_column('application_transactions', 'amount',
               existing_type=sa.Float(precision=2),
               type_=sa.REAL(),
               existing_nullable=False)
    op.add_column('admission_visitors', sa.Column('check_in_time', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.add_column('admission_visitors', sa.Column('check_out_time', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('admission_visitors', sa.Column('visit_status', sa.VARCHAR(length=30), server_default=sa.text("'checked_in'::character varying"), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'academic_year_departments', type_='foreignkey')
    op.drop_constraint(None, 'academic_year_departments', type_='foreignkey')
    op.drop_constraint(None, 'academic_year_departments', type_='foreignkey')
    op.create_table('castes',
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('community_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('deleted_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['community_id'], ['communities.id'], name=op.f('castes_community_id_fkey')),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('castes_created_by_fkey'), initially='DEFERRED', deferrable=True),
    sa.ForeignKeyConstraint(['deleted_by'], ['users.id'], name=op.f('castes_deleted_by_fkey'), initially='DEFERRED', deferrable=True),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f('castes_updated_by_fkey'), initially='DEFERRED', deferrable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('castes_pkey')),
    sa.UniqueConstraint('name', name=op.f('castes_name_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('concessions',
    sa.Column('student_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('college_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('fee_head_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('fee_sub_head_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('amount', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=True),
    sa.Column('percent', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True),
    sa.Column('start_date', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('end_date', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('proof_file', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('meta', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('deleted_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name='concessions_created_by_fkey', initially='DEFERRED', deferrable=True),
    sa.ForeignKeyConstraint(['deleted_by'], ['users.id'], name='concessions_deleted_by_fkey', initially='DEFERRED', deferrable=True),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name='concessions_updated_by_fkey', initially='DEFERRED', deferrable=True),
    sa.PrimaryKeyConstraint('id', name='concessions_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index(op.f('ix_concessions_student_id'), 'concessions', ['student_id'], unique=False)
    op.create_index(op.f('ix_concessions_fee_sub_head_id'), 'concessions', ['fee_sub_head_id'], unique=False)
    op.create_index(op.f('ix_concessions_fee_head_id'), 'concessions', ['fee_head_id'], unique=False)
    op.create_index(op.f('ix_concessions_college_id'), 'concessions', ['college_id'], unique=False)
    op.create_table('hostels',
    sa.Column('name', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('institution_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('code', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('meta', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('deleted_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name='hostels_created_by_fkey', initially='DEFERRED', deferrable=True),
    sa.ForeignKeyConstraint(['deleted_by'], ['users.id'], name='hostels_deleted_by_fkey', initially='DEFERRED', deferrable=True),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name='hostels_updated_by_fkey', initially='DEFERRED', deferrable=True),
    sa.PrimaryKeyConstraint('id', name='hostels_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index(op.f('ix_hostels_institution_id'), 'hostels', ['institution_id'], unique=False)
    op.create_index(op.f('ix_hostels_code'), 'hostels', ['code'], unique=False)
    op.create_table('hostel_rooms',
    sa.Column('hostel_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('room_no', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('room_type', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('capacity', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('ac', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('meta', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('deleted_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('hostel_rooms_created_by_fkey'), initially='DEFERRED', deferrable=True),
    sa.ForeignKeyConstraint(['deleted_by'], ['users.id'], name=op.f('hostel_rooms_deleted_by_fkey'), initially='DEFERRED', deferrable=True),
    sa.ForeignKeyConstraint(['hostel_id'], ['hostels.id'], name=op.f('hostel_rooms_hostel_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f('hostel_rooms_updated_by_fkey'), initially='DEFERRED', deferrable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('hostel_rooms_pkey'))
    )
    op.create_index(op.f('ix_hostel_rooms_hostel_id'), 'hostel_rooms', ['hostel_id'], unique=False)
    op.create_table('payment_recall_requests',
    sa.Column('payment_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('requested_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('reason', sa.VARCHAR(length=1000), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('processed_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('processed_at', sa.VARCHAR(length=30), autoincrement=False, nullable=True),
    sa.Column('meta', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('deleted_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('payment_recall_requests_created_by_fkey'), initially='DEFERRED', deferrable=True),
    sa.ForeignKeyConstraint(['deleted_by'], ['users.id'], name=op.f('payment_recall_requests_deleted_by_fkey'), initially='DEFERRED', deferrable=True),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], name=op.f('payment_recall_requests_payment_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['processed_by'], ['users.id'], name=op.f('payment_recall_requests_processed_by_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['requested_by'], ['users.id'], name=op.f('payment_recall_requests_requested_by_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f('payment_recall_requests_updated_by_fkey'), initially='DEFERRED', deferrable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('payment_recall_requests_pkey'))
    )
    op.create_index(op.f('ix_payment_recall_requests_payment_id'), 'payment_recall_requests', ['payment_id'], unique=False)
    op.create_table('transport_fee_structures',
    sa.Column('college_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('batch', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('route_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('fee_head_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('fee_sub_head_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('amount', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=False),
    sa.Column('status', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('meta', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('deleted_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('transport_fee_structures_created_by_fkey'), initially='DEFERRED', deferrable=True),
    sa.ForeignKeyConstraint(['deleted_by'], ['users.id'], name=op.f('transport_fee_structures_deleted_by_fkey'), initially='DEFERRED', deferrable=True),
    sa.ForeignKeyConstraint(['route_id'], ['transport_routes.id'], name=op.f('transport_fee_structures_route_id_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f('transport_fee_structures_updated_by_fkey'), initially='DEFERRED', deferrable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('transport_fee_structures_pkey'))
    )
    op.create_index(op.f('ix_transport_fee_structures_route_id'), 'transport_fee_structures', ['route_id'], unique=False)
    op.create_index(op.f('ix_transport_fee_structures_fee_sub_head_id'), 'transport_fee_structures', ['fee_sub_head_id'], unique=False)
    op.create_index(op.f('ix_transport_fee_structures_fee_head_id'), 'transport_fee_structures', ['fee_head_id'], unique=False)
    op.create_index(op.f('ix_transport_fee_structures_college_id'), 'transport_fee_structures', ['college_id'], unique=False)
    op.create_index(op.f('ix_transport_fee_structures_batch'), 'transport_fee_structures', ['batch'], unique=False)
    op.create_table('concession_audits',
    sa.Column('concession_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('action', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('performed_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('notes', sa.VARCHAR(length=1000), autoincrement=False, nullable=True),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('deleted_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['concession_id'], ['concessions.id'], name=op.f('concession_audits_concession_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('concession_audits_created_by_fkey'), initially='DEFERRED', deferrable=True),
    sa.ForeignKeyConstraint(['deleted_by'], ['users.id'], name=op.f('concession_audits_deleted_by_fkey'), initially='DEFERRED', deferrable=True),
    sa.ForeignKeyConstraint(['performed_by'], ['users.id'], name=op.f('concession_audits_performed_by_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f('concession_audits_updated_by_fkey'), initially='DEFERRED', deferrable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('concession_audits_pkey'))
    )
    op.create_index(op.f('ix_concession_audits_concession_id'), 'concession_audits', ['concession_id'], unique=False)
    op.create_table('religions',
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('deleted_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('religions_created_by_fkey'), initially='DEFERRED', deferrable=True),
    sa.ForeignKeyConstraint(['deleted_by'], ['users.id'], name=op.f('religions_deleted_by_fkey'), initially='DEFERRED', deferrable=True),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f('religions_updated_by_fkey'), initially='DEFERRED', deferrable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('religions_pkey')),
    sa.UniqueConstraint('name', name=op.f('religions_name_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('communities',
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('deleted_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('communities_created_by_fkey'), initially='DEFERRED', deferrable=True),
    sa.ForeignKeyConstraint(['deleted_by'], ['users.id'], name=op.f('communities_deleted_by_fkey'), initially='DEFERRED', deferrable=True),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f('communities_updated_by_fkey'), initially='DEFERRED', deferrable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('communities_pkey')),
    sa.UniqueConstraint('name', name=op.f('communities_name_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('hostel_fee_structures',
    sa.Column('college_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('hostel_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('room_type', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('ac', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('financial_year_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('fee_head_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('fee_sub_head_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('amount', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=False),
    sa.Column('installments', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('status', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('deleted_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('hostel_fee_structures_created_by_fkey'), initially='DEFERRED', deferrable=True),
    sa.ForeignKeyConstraint(['deleted_by'], ['users.id'], name=op.f('hostel_fee_structures_deleted_by_fkey'), initially='DEFERRED', deferrable=True),
    sa.ForeignKeyConstraint(['hostel_id'], ['hostels.id'], name=op.f('hostel_fee_structures_hostel_id_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f('hostel_fee_structures_updated_by_fkey'), initially='DEFERRED', deferrable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('hostel_fee_structures_pkey'))
    )
    op.create_index(op.f('ix_hostel_fee_structures_room_type'), 'hostel_fee_structures', ['room_type'], unique=False)
    op.create_index(op.f('ix_hostel_fee_structures_hostel_id'), 'hostel_fee_structures', ['hostel_id'], unique=False)
    op.create_index(op.f('ix_hostel_fee_structures_financial_year_id'), 'hostel_fee_structures', ['financial_year_id'], unique=False)
    op.create_index(op.f('ix_hostel_fee_structures_fee_sub_head_id'), 'hostel_fee_structures', ['fee_sub_head_id'], unique=False)
    op.create_index(op.f('ix_hostel_fee_structures_fee_head_id'), 'hostel_fee_structures', ['fee_head_id'], unique=False)
    op.create_index(op.f('ix_hostel_fee_structures_college_id'), 'hostel_fee_structures', ['college_id'], unique=False)
    op.create_table('transport_routes',
    sa.Column('college_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=150), autoincrement=False, nullable=False),
    sa.Column('code', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('meta', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('deleted_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name='transport_routes_created_by_fkey', initially='DEFERRED', deferrable=True),
    sa.ForeignKeyConstraint(['deleted_by'], ['users.id'], name='transport_routes_deleted_by_fkey', initially='DEFERRED', deferrable=True),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name='transport_routes_updated_by_fkey', initially='DEFERRED', deferrable=True),
    sa.PrimaryKeyConstraint('id', name='transport_routes_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index(op.f('ix_transport_routes_college_id'), 'transport_routes', ['college_id'], unique=False)
    op.create_index(op.f('ix_transport_routes_code'), 'transport_routes', ['code'], unique=False)
    op.create_table('transport_buses',
    sa.Column('route_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('bus_number', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('seats', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('meta', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('deleted_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('transport_buses_created_by_fkey'), initially='DEFERRED', deferrable=True),
    sa.ForeignKeyConstraint(['deleted_by'], ['users.id'], name=op.f('transport_buses_deleted_by_fkey'), initially='DEFERRED', deferrable=True),
    sa.ForeignKeyConstraint(['route_id'], ['transport_routes.id'], name=op.f('transport_buses_route_id_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f('transport_buses_updated_by_fkey'), initially='DEFERRED', deferrable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('transport_buses_pkey'))
    )
    op.create_index(op.f('ix_transport_buses_route_id'), 'transport_buses', ['route_id'], unique=False)
    # ### end Alembic commands ###
