"""

Revision ID: 8bc2c7b3ea21
Revises: 95127fa5bc37
Create Date: 2026-01-22 08:47:45.044599

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8bc2c7b3ea21'
down_revision: Union[str, Sequence[str], None] = '95127fa5bc37'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payment_recall_requests_payment_id'), table_name='payment_recall_requests')
    op.drop_table('payment_recall_requests')
    op.add_column('admission_students', sa.Column('application_number', sa.String(length=50), nullable=False))
    op.create_index(op.f('ix_admission_students_application_number'), 'admission_students', ['application_number'], unique=True)
    op.alter_column('application_transactions', 'amount',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=2),
               existing_nullable=False)
    op.alter_column('invoice_line_items', 'amount',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=2),
               existing_nullable=False)
    op.alter_column('invoice_line_items', 'discount_amount',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=2),
               existing_nullable=True)
    op.alter_column('invoice_line_items', 'tax_amount',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=2),
               existing_nullable=True)
    op.alter_column('invoice_line_items', 'net_amount',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=2),
               existing_nullable=False)
    op.alter_column('invoices', 'amount',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=2),
               existing_nullable=False)
    op.alter_column('invoices', 'paid_amount',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=2),
               existing_nullable=False)
    op.alter_column('invoices', 'balance_due',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=2),
               existing_nullable=False)
    op.alter_column('payments', 'amount',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=2),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('payments', 'amount',
               existing_type=sa.Float(precision=2),
               type_=sa.REAL(),
               existing_nullable=False)
    op.alter_column('invoices', 'balance_due',
               existing_type=sa.Float(precision=2),
               type_=sa.REAL(),
               existing_nullable=False)
    op.alter_column('invoices', 'paid_amount',
               existing_type=sa.Float(precision=2),
               type_=sa.REAL(),
               existing_nullable=False)
    op.alter_column('invoices', 'amount',
               existing_type=sa.Float(precision=2),
               type_=sa.REAL(),
               existing_nullable=False)
    op.alter_column('invoice_line_items', 'net_amount',
               existing_type=sa.Float(precision=2),
               type_=sa.REAL(),
               existing_nullable=False)
    op.alter_column('invoice_line_items', 'tax_amount',
               existing_type=sa.Float(precision=2),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('invoice_line_items', 'discount_amount',
               existing_type=sa.Float(precision=2),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('invoice_line_items', 'amount',
               existing_type=sa.Float(precision=2),
               type_=sa.REAL(),
               existing_nullable=False)
    op.alter_column('application_transactions', 'amount',
               existing_type=sa.Float(precision=2),
               type_=sa.REAL(),
               existing_nullable=False)
    op.drop_index(op.f('ix_admission_students_application_number'), table_name='admission_students')
    op.drop_column('admission_students', 'application_number')
    op.create_table('payment_recall_requests',
    sa.Column('payment_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('requested_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('reason', sa.VARCHAR(length=1000), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('processed_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('processed_at', sa.VARCHAR(length=30), autoincrement=False, nullable=True),
    sa.Column('meta', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('deleted_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('payment_recall_requests_created_by_fkey'), initially='DEFERRED', deferrable=True),
    sa.ForeignKeyConstraint(['deleted_by'], ['users.id'], name=op.f('payment_recall_requests_deleted_by_fkey'), initially='DEFERRED', deferrable=True),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], name=op.f('payment_recall_requests_payment_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['processed_by'], ['users.id'], name=op.f('payment_recall_requests_processed_by_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['requested_by'], ['users.id'], name=op.f('payment_recall_requests_requested_by_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f('payment_recall_requests_updated_by_fkey'), initially='DEFERRED', deferrable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('payment_recall_requests_pkey'))
    )
    op.create_index(op.f('ix_payment_recall_requests_payment_id'), 'payment_recall_requests', ['payment_id'], unique=False)
    # ### end Alembic commands ###
