"""professional_db_schema_fixes

Revision ID: 92b3da52483d
Revises: 20260224_demand_subhead
Create Date: 2026-02-25 14:30:24.466586

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '92b3da52483d'
down_revision: Union[str, Sequence[str], None] = '20260224_demand_subhead'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('academic_year_courses', 'application_fee',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=12, scale=2),
               existing_nullable=False)
    op.create_index(op.f('ix_academic_year_courses_academic_year_id'), 'academic_year_courses', ['academic_year_id'], unique=False)
    op.create_index(op.f('ix_academic_year_courses_course_id'), 'academic_year_courses', ['course_id'], unique=False)
    op.create_index(op.f('ix_academic_year_courses_deleted_at'), 'academic_year_courses', ['deleted_at'], unique=False)
    op.create_unique_constraint('uq_academic_year_course', 'academic_year_courses', ['academic_year_id', 'course_id'])
    op.create_index(op.f('ix_academic_years_deleted_at'), 'academic_years', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_academic_years_institution_id'), 'academic_years', ['institution_id'], unique=False)
    op.create_unique_constraint('uq_institution_year_name', 'academic_years', ['institution_id', 'year_name'])
    op.alter_column('admission_form_verifications', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.alter_column('admission_form_verifications', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.create_index(op.f('ix_admission_form_verifications_application_received_by'), 'admission_form_verifications', ['application_received_by'], unique=False)
    op.create_index(op.f('ix_admission_form_verifications_certificate_verified_by'), 'admission_form_verifications', ['certificate_verified_by'], unique=False)
    op.create_index(op.f('ix_admission_form_verifications_deleted_at'), 'admission_form_verifications', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_admission_form_verifications_form_printed_by'), 'admission_form_verifications', ['form_printed_by'], unique=False)
    op.create_index(op.f('ix_admission_form_verifications_provisionally_allotted_by'), 'admission_form_verifications', ['provisionally_allotted_by'], unique=False)
    op.create_foreign_key(None, 'admission_form_verifications', 'users', ['certificate_verified_by'], ['id'], initially='DEFERRED', deferrable=True, use_alter=True)
    op.create_foreign_key(None, 'admission_form_verifications', 'users', ['form_printed_by'], ['id'], initially='DEFERRED', deferrable=True, use_alter=True)
    op.create_foreign_key(None, 'admission_form_verifications', 'users', ['application_received_by'], ['id'], initially='DEFERRED', deferrable=True, use_alter=True)
    op.create_foreign_key(None, 'admission_form_verifications', 'users', ['provisionally_allotted_by'], ['id'], initially='DEFERRED', deferrable=True, use_alter=True)
    op.alter_column('admission_required_certificates', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=False)
    op.alter_column('admission_required_certificates', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=False)
    op.create_index(op.f('ix_admission_required_certificates_deleted_at'), 'admission_required_certificates', ['deleted_at'], unique=False)
    op.alter_column('admission_students', 'parent_income',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=12, scale=2),
               existing_nullable=True)
    op.create_index(op.f('ix_admission_students_deleted_at'), 'admission_students', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_admission_students_fee_structure_locked_by'), 'admission_students', ['fee_structure_locked_by'], unique=False)
    op.alter_column('admission_types', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('admission_types', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_admission_types_deleted_at'), 'admission_types', ['deleted_at'], unique=False)
    op.alter_column('admission_visitors', 'visit_status',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('PENDING', 'CHECKED_IN', 'CHECKED_OUT', 'CANCELLED', name='visitstatus', native_enum=False),
               existing_nullable=False,
               existing_server_default=sa.text("'CHECKED_IN'::character varying"))
    op.drop_index(op.f('ix_admission_visitors_check_in_time'), table_name='admission_visitors')
    op.drop_index(op.f('ix_admission_visitors_check_out_time'), table_name='admission_visitors')
    op.drop_index(op.f('ix_admission_visitors_visit_status'), table_name='admission_visitors')
    op.create_index(op.f('ix_admission_visitors_deleted_at'), 'admission_visitors', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_admission_visitors_institution_id'), 'admission_visitors', ['institution_id'], unique=False)
    op.alter_column('application_transactions', 'amount',
               existing_type=sa.REAL(),
               type_=sa.Numeric(precision=12, scale=2),
               existing_nullable=False)
    op.create_index(op.f('ix_application_transactions_cash_counter_id'), 'application_transactions', ['cash_counter_id'], unique=False)
    op.create_index(op.f('ix_application_transactions_deleted_at'), 'application_transactions', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_cash_counters_deleted_at'), 'cash_counters', ['deleted_at'], unique=False)
    op.create_foreign_key(None, 'cash_counters', 'institutions', ['institution_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_castes_community_id'), 'castes', ['community_id'], unique=False)
    op.create_index(op.f('ix_castes_deleted_at'), 'castes', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_classes_course_id'), 'classes', ['course_id'], unique=False)
    op.create_index(op.f('ix_classes_deleted_at'), 'classes', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_communities_deleted_at'), 'communities', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_concession_audits_deleted_at'), 'concession_audits', ['deleted_at'], unique=False)
    op.add_column('concessions', sa.Column('institution_id', sa.UUID(), nullable=True))
    op.execute("UPDATE concessions SET institution_id = college_id")
    op.alter_column('concessions', 'institution_id', nullable=False)
    op.execute("UPDATE concessions SET start_date = NULL WHERE start_date IS NOT NULL AND start_date !~ '^\\d{4}-\\d{2}-\\d{2}$'")
    op.execute("UPDATE concessions SET end_date = NULL WHERE end_date IS NOT NULL AND end_date !~ '^\\d{4}-\\d{2}-\\d{2}$'")
    op.alter_column('concessions', 'start_date',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Date(),
               existing_nullable=True,
               postgresql_using='start_date::date')
    op.alter_column('concessions', 'end_date',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Date(),
               existing_nullable=True,
               postgresql_using='end_date::date')
    op.drop_index(op.f('ix_concessions_college_id'), table_name='concessions')
    op.create_index(op.f('ix_concessions_deleted_at'), 'concessions', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_concessions_institution_id'), 'concessions', ['institution_id'], unique=False)
    op.drop_constraint(op.f('concessions_college_id_fkey'), 'concessions', type_='foreignkey')
    op.create_foreign_key(None, 'concessions', 'institutions', ['institution_id'], ['id'], ondelete='CASCADE')
    op.drop_column('concessions', 'college_id')
    op.create_index(op.f('ix_consultancies_deleted_at'), 'consultancies', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_consultancy_references_consultancy_id'), 'consultancy_references', ['consultancy_id'], unique=False)
    op.create_index(op.f('ix_consultancy_references_deleted_at'), 'consultancy_references', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_courses_deleted_at'), 'courses', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_courses_department_id'), 'courses', ['department_id'], unique=False)
    op.create_index(op.f('ix_demand_batches_deleted_at'), 'demand_batches', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_demand_items_deleted_at'), 'demand_items', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_demand_items_fee_head_id'), 'demand_items', ['fee_head_id'], unique=False)
    op.alter_column('department_change_requests', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.alter_column('department_change_requests', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.create_index(op.f('ix_department_change_requests_current_department_id'), 'department_change_requests', ['current_department_id'], unique=False)
    op.create_index(op.f('ix_department_change_requests_deleted_at'), 'department_change_requests', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_department_change_requests_requested_by'), 'department_change_requests', ['requested_by'], unique=False)
    op.create_index(op.f('ix_department_change_requests_requested_department_id'), 'department_change_requests', ['requested_department_id'], unique=False)
    op.create_index(op.f('ix_department_change_requests_reviewed_by'), 'department_change_requests', ['reviewed_by'], unique=False)
    op.create_foreign_key(None, 'department_change_requests', 'users', ['requested_by'], ['id'], initially='DEFERRED', deferrable=True, use_alter=True)
    op.create_foreign_key(None, 'department_change_requests', 'users', ['reviewed_by'], ['id'], initially='DEFERRED', deferrable=True, use_alter=True)
    op.create_index(op.f('ix_departments_deleted_at'), 'departments', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_departments_institution_id'), 'departments', ['institution_id'], unique=False)
    op.alter_column('diploma_details', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.alter_column('diploma_details', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.create_index(op.f('ix_diploma_details_deleted_at'), 'diploma_details', ['deleted_at'], unique=False)
    op.alter_column('document_types', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=False)
    op.alter_column('document_types', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=False)
    op.create_index(op.f('ix_document_types_deleted_at'), 'document_types', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_fee_heads_deleted_at'), 'fee_heads', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_fee_heads_institution_id'), 'fee_heads', ['institution_id'], unique=False)
    op.create_index(op.f('ix_fee_structure_items_deleted_at'), 'fee_structure_items', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_fee_structures_deleted_at'), 'fee_structures', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_fee_sub_heads_deleted_at'), 'fee_sub_heads', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_financial_years_deleted_at'), 'financial_years', ['deleted_at'], unique=False)
    op.create_unique_constraint('uq_institution_financial_year_name', 'financial_years', ['institution_id', 'name'])
    op.add_column('hostel_fee_structures', sa.Column('institution_id', sa.UUID(), nullable=True))
    op.execute("UPDATE hostel_fee_structures SET institution_id = college_id")
    op.alter_column('hostel_fee_structures', 'institution_id', nullable=False)
    op.drop_index(op.f('ix_hostel_fee_structures_college_id'), table_name='hostel_fee_structures')
    op.create_index(op.f('ix_hostel_fee_structures_deleted_at'), 'hostel_fee_structures', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_hostel_fee_structures_institution_id'), 'hostel_fee_structures', ['institution_id'], unique=False)
    op.drop_constraint(op.f('hostel_fee_structures_college_id_fkey'), 'hostel_fee_structures', type_='foreignkey')
    op.create_foreign_key(None, 'hostel_fee_structures', 'institutions', ['institution_id'], ['id'], ondelete='CASCADE')
    op.drop_column('hostel_fee_structures', 'college_id')
    op.create_index(op.f('ix_hostel_rooms_deleted_at'), 'hostel_rooms', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_hostels_deleted_at'), 'hostels', ['deleted_at'], unique=False)
    op.alter_column('hsc_details', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.alter_column('hsc_details', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.create_index(op.f('ix_hsc_details_deleted_at'), 'hsc_details', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_institutions_deleted_at'), 'institutions', ['deleted_at'], unique=False)
    op.alter_column('invoice_line_items', 'amount',
               existing_type=sa.REAL(),
               type_=sa.Numeric(precision=12, scale=2),
               existing_nullable=False)
    op.alter_column('invoice_line_items', 'discount_amount',
               existing_type=sa.REAL(),
               type_=sa.Numeric(precision=12, scale=2),
               existing_nullable=True)
    op.alter_column('invoice_line_items', 'tax_amount',
               existing_type=sa.REAL(),
               type_=sa.Numeric(precision=12, scale=2),
               existing_nullable=True)
    op.alter_column('invoice_line_items', 'net_amount',
               existing_type=sa.REAL(),
               type_=sa.Numeric(precision=12, scale=2),
               existing_nullable=False)
    op.create_index(op.f('ix_invoice_line_items_deleted_at'), 'invoice_line_items', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_invoice_line_items_fee_head_id'), 'invoice_line_items', ['fee_head_id'], unique=False)
    op.create_index(op.f('ix_invoice_status_history_changed_by'), 'invoice_status_history', ['changed_by'], unique=False)
    op.create_index(op.f('ix_invoice_status_history_deleted_at'), 'invoice_status_history', ['deleted_at'], unique=False)
    op.alter_column('invoices', 'amount',
               existing_type=sa.REAL(),
               type_=sa.Numeric(precision=12, scale=2),
               existing_nullable=False)
    op.alter_column('invoices', 'paid_amount',
               existing_type=sa.REAL(),
               type_=sa.Numeric(precision=12, scale=2),
               existing_nullable=False)
    op.alter_column('invoices', 'balance_due',
               existing_type=sa.REAL(),
               type_=sa.Numeric(precision=12, scale=2),
               existing_nullable=False)
    op.create_index(op.f('ix_invoices_deleted_at'), 'invoices', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_lead_followups_deleted_at'), 'lead_followups', ['deleted_at'], unique=False)
    op.create_foreign_key(None, 'lead_followups', 'users', ['created_by'], ['id'], initially='DEFERRED', deferrable=True, use_alter=True)
    op.create_index(op.f('ix_modules_deleted_at'), 'modules', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_other_references_deleted_at'), 'other_references', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_other_references_reference_id'), 'other_references', ['reference_id'], unique=True)
    op.execute("UPDATE payment_recall_requests SET processed_at = NULL WHERE processed_at IS NOT NULL AND processed_at !~ '^\\d{4}-\\d{2}-\\d{2}'")
    op.alter_column('payment_recall_requests', 'processed_at',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               postgresql_using='processed_at::timestamp with time zone')
    op.create_index(op.f('ix_payment_recall_requests_deleted_at'), 'payment_recall_requests', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_payment_recall_requests_processed_by'), 'payment_recall_requests', ['processed_by'], unique=False)
    op.create_index(op.f('ix_payment_recall_requests_requested_by'), 'payment_recall_requests', ['requested_by'], unique=False)
    op.alter_column('payments', 'amount',
               existing_type=sa.REAL(),
               type_=sa.Numeric(precision=12, scale=2),
               existing_nullable=False)
    op.create_index(op.f('ix_payments_cash_counter_id'), 'payments', ['cash_counter_id'], unique=False)
    op.create_index(op.f('ix_payments_deleted_at'), 'payments', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_permissions_deleted_at'), 'permissions', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_person_types_deleted_at'), 'person_types', ['deleted_at'], unique=False)
    op.alter_column('pg_details', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.alter_column('pg_details', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.create_index(op.f('ix_pg_details_deleted_at'), 'pg_details', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_religions_deleted_at'), 'religions', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_role_permissions_deleted_at'), 'role_permissions', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_role_permissions_role_id'), 'role_permissions', ['role_id'], unique=False)
    op.create_index(op.f('ix_role_permissions_screen_id'), 'role_permissions', ['screen_id'], unique=False)
    op.create_unique_constraint('uq_role_screen', 'role_permissions', ['role_id', 'screen_id'])
    op.create_index(op.f('ix_roles_deleted_at'), 'roles', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_screens_deleted_at'), 'screens', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_screens_module_id'), 'screens', ['module_id'], unique=False)
    op.create_index(op.f('ix_screens_parent_id'), 'screens', ['parent_id'], unique=False)
    op.alter_column('seat_quotas', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=False)
    op.alter_column('seat_quotas', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=False)
    op.create_index(op.f('ix_seat_quotas_deleted_at'), 'seat_quotas', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_semester_periods_academic_year_id'), 'semester_periods', ['academic_year_id'], unique=False)
    op.create_index(op.f('ix_semester_periods_deleted_at'), 'semester_periods', ['deleted_at'], unique=False)
    op.alter_column('sslc_details', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.alter_column('sslc_details', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.create_index(op.f('ix_sslc_details_deleted_at'), 'sslc_details', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_staff_references_deleted_at'), 'staff_references', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_staff_references_reference_id'), 'staff_references', ['reference_id'], unique=True)
    op.create_index(op.f('ix_student_references_deleted_at'), 'student_references', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_student_references_reference_id'), 'student_references', ['reference_id'], unique=True)
    op.execute("UPDATE submitted_certificates SET file_size = NULL WHERE file_size IS NOT NULL AND file_size !~ '^[0-9]+$'")
    op.alter_column('submitted_certificates', 'file_size',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Integer(),
               existing_nullable=True,
               postgresql_using='file_size::integer')
    op.alter_column('submitted_certificates', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.alter_column('submitted_certificates', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.create_index(op.f('ix_submitted_certificates_deleted_at'), 'submitted_certificates', ['deleted_at'], unique=False)
    op.create_foreign_key(None, 'submitted_certificates', 'users', ['received_by'], ['id'], initially='DEFERRED', deferrable=True, use_alter=True)
    op.create_foreign_key(None, 'submitted_certificates', 'users', ['verified_by'], ['id'], initially='DEFERRED', deferrable=True, use_alter=True)
    op.create_index(op.f('ix_transport_buses_deleted_at'), 'transport_buses', ['deleted_at'], unique=False)
    op.add_column('transport_fee_structures', sa.Column('institution_id', sa.UUID(), nullable=True))
    op.execute("UPDATE transport_fee_structures SET institution_id = college_id")
    op.alter_column('transport_fee_structures', 'institution_id', nullable=False)
    op.drop_index(op.f('ix_transport_fee_structures_college_id'), table_name='transport_fee_structures')
    op.create_index(op.f('ix_transport_fee_structures_deleted_at'), 'transport_fee_structures', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_transport_fee_structures_institution_id'), 'transport_fee_structures', ['institution_id'], unique=False)
    op.drop_constraint(op.f('transport_fee_structures_college_id_fkey'), 'transport_fee_structures', type_='foreignkey')
    op.create_foreign_key(None, 'transport_fee_structures', 'institutions', ['institution_id'], ['id'], ondelete='CASCADE')
    op.drop_column('transport_fee_structures', 'college_id')
    op.add_column('transport_routes', sa.Column('institution_id', sa.UUID(), nullable=True))
    op.execute("UPDATE transport_routes SET institution_id = college_id")
    op.alter_column('transport_routes', 'institution_id', nullable=False)
    op.drop_index(op.f('ix_transport_routes_college_id'), table_name='transport_routes')
    op.create_index(op.f('ix_transport_routes_deleted_at'), 'transport_routes', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_transport_routes_institution_id'), 'transport_routes', ['institution_id'], unique=False)
    op.drop_constraint(op.f('transport_routes_college_id_fkey'), 'transport_routes', type_='foreignkey')
    op.create_foreign_key(None, 'transport_routes', 'institutions', ['institution_id'], ['id'], ondelete='CASCADE')
    op.drop_column('transport_routes', 'college_id')
    op.create_index(op.f('ix_user_permissions_deleted_at'), 'user_permissions', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_user_permissions_screen_id'), 'user_permissions', ['screen_id'], unique=False)
    op.create_index(op.f('ix_user_permissions_user_id'), 'user_permissions', ['user_id'], unique=False)
    op.create_unique_constraint('uq_user_screen', 'user_permissions', ['user_id', 'screen_id'])
    op.create_index(op.f('ix_users_deleted_at'), 'users', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_users_role_id'), 'users', ['role_id'], unique=False)
    op.create_index(op.f('ix_vendor_visitors_deleted_at'), 'vendor_visitors', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_visitors_deleted_at'), 'visitors', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_visitors_department_id'), 'visitors', ['department_id'], unique=False)
    op.create_index(op.f('ix_visitors_institution_id'), 'visitors', ['institution_id'], unique=False)
    op.create_index(op.f('ix_visitors_person_type_id'), 'visitors', ['person_type_id'], unique=False)
    
    # --- Manually added CHECK constraints (not detected by autogenerate) ---
    op.create_check_constraint('ck_course_duration_positive', 'courses', 'course_duration_years > 0')
    op.create_check_constraint('ck_total_semesters_positive', 'courses', 'total_semesters > 0')
    op.create_check_constraint('ck_academic_year_dates', 'academic_years', 'from_date < to_date')
    op.create_check_constraint('ck_application_fee_non_negative', 'academic_year_courses', 'application_fee >= 0')
    op.create_check_constraint('ck_semester_period_dates', 'semester_periods', 'from_date < to_date')
    op.create_check_constraint('ck_invoice_amount_non_negative', 'invoices', 'amount >= 0')
    op.create_check_constraint('ck_invoice_paid_amount_non_negative', 'invoices', 'paid_amount >= 0')
    op.create_check_constraint('ck_invoice_balance_non_negative', 'invoices', 'balance_due >= 0')
    op.create_check_constraint('ck_line_item_amount_non_negative', 'invoice_line_items', 'amount >= 0')
    op.create_check_constraint('ck_line_item_net_non_negative', 'invoice_line_items', 'net_amount >= 0')
    op.create_check_constraint('ck_payment_amount_positive', 'payments', 'amount > 0')
    op.create_check_constraint('ck_app_txn_amount_positive', 'application_transactions', 'amount > 0')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_visitors_person_type_id'), table_name='visitors')
    op.drop_index(op.f('ix_visitors_institution_id'), table_name='visitors')
    op.drop_index(op.f('ix_visitors_department_id'), table_name='visitors')
    op.drop_index(op.f('ix_visitors_deleted_at'), table_name='visitors')
    op.drop_index(op.f('ix_vendor_visitors_deleted_at'), table_name='vendor_visitors')
    op.drop_index(op.f('ix_users_role_id'), table_name='users')
    op.drop_index(op.f('ix_users_deleted_at'), table_name='users')
    op.drop_constraint('uq_user_screen', 'user_permissions', type_='unique')
    op.drop_index(op.f('ix_user_permissions_user_id'), table_name='user_permissions')
    op.drop_index(op.f('ix_user_permissions_screen_id'), table_name='user_permissions')
    op.drop_index(op.f('ix_user_permissions_deleted_at'), table_name='user_permissions')
    op.add_column('transport_routes', sa.Column('college_id', sa.UUID(), autoincrement=False, nullable=True))
    op.execute("UPDATE transport_routes SET college_id = institution_id")
    op.alter_column('transport_routes', 'college_id', nullable=False)
    op.drop_constraint(None, 'transport_routes', type_='foreignkey')
    op.create_foreign_key(op.f('transport_routes_college_id_fkey'), 'transport_routes', 'institutions', ['college_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_transport_routes_institution_id'), table_name='transport_routes')
    op.drop_index(op.f('ix_transport_routes_deleted_at'), table_name='transport_routes')
    op.create_index(op.f('ix_transport_routes_college_id'), 'transport_routes', ['college_id'], unique=False)
    op.drop_column('transport_routes', 'institution_id')
    op.add_column('transport_fee_structures', sa.Column('college_id', sa.UUID(), autoincrement=False, nullable=True))
    op.execute("UPDATE transport_fee_structures SET college_id = institution_id")
    op.alter_column('transport_fee_structures', 'college_id', nullable=False)
    op.drop_constraint(None, 'transport_fee_structures', type_='foreignkey')
    op.create_foreign_key(op.f('transport_fee_structures_college_id_fkey'), 'transport_fee_structures', 'institutions', ['college_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_transport_fee_structures_institution_id'), table_name='transport_fee_structures')
    op.drop_index(op.f('ix_transport_fee_structures_deleted_at'), table_name='transport_fee_structures')
    op.create_index(op.f('ix_transport_fee_structures_college_id'), 'transport_fee_structures', ['college_id'], unique=False)
    op.drop_column('transport_fee_structures', 'institution_id')
    op.drop_index(op.f('ix_transport_buses_deleted_at'), table_name='transport_buses')
    op.drop_constraint(None, 'submitted_certificates', type_='foreignkey')
    op.drop_constraint(None, 'submitted_certificates', type_='foreignkey')
    op.drop_index(op.f('ix_submitted_certificates_deleted_at'), table_name='submitted_certificates')
    op.alter_column('submitted_certificates', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('submitted_certificates', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('submitted_certificates', 'file_size',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.drop_index(op.f('ix_student_references_reference_id'), table_name='student_references')
    op.drop_index(op.f('ix_student_references_deleted_at'), table_name='student_references')
    op.drop_index(op.f('ix_staff_references_reference_id'), table_name='staff_references')
    op.drop_index(op.f('ix_staff_references_deleted_at'), table_name='staff_references')
    op.drop_index(op.f('ix_sslc_details_deleted_at'), table_name='sslc_details')
    op.alter_column('sslc_details', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('sslc_details', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.drop_index(op.f('ix_semester_periods_deleted_at'), table_name='semester_periods')
    op.drop_index(op.f('ix_semester_periods_academic_year_id'), table_name='semester_periods')
    op.drop_index(op.f('ix_seat_quotas_deleted_at'), table_name='seat_quotas')
    op.alter_column('seat_quotas', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('seat_quotas', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_index(op.f('ix_screens_parent_id'), table_name='screens')
    op.drop_index(op.f('ix_screens_module_id'), table_name='screens')
    op.drop_index(op.f('ix_screens_deleted_at'), table_name='screens')
    op.drop_index(op.f('ix_roles_deleted_at'), table_name='roles')
    op.drop_constraint('uq_role_screen', 'role_permissions', type_='unique')
    op.drop_index(op.f('ix_role_permissions_screen_id'), table_name='role_permissions')
    op.drop_index(op.f('ix_role_permissions_role_id'), table_name='role_permissions')
    op.drop_index(op.f('ix_role_permissions_deleted_at'), table_name='role_permissions')
    op.drop_index(op.f('ix_religions_deleted_at'), table_name='religions')
    op.drop_index(op.f('ix_pg_details_deleted_at'), table_name='pg_details')
    op.alter_column('pg_details', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('pg_details', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.drop_index(op.f('ix_person_types_deleted_at'), table_name='person_types')
    op.drop_index(op.f('ix_permissions_deleted_at'), table_name='permissions')
    op.drop_index(op.f('ix_payments_deleted_at'), table_name='payments')
    op.drop_index(op.f('ix_payments_cash_counter_id'), table_name='payments')
    op.alter_column('payments', 'amount',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=sa.REAL(),
               existing_nullable=False)
    op.drop_index(op.f('ix_payment_recall_requests_requested_by'), table_name='payment_recall_requests')
    op.drop_index(op.f('ix_payment_recall_requests_processed_by'), table_name='payment_recall_requests')
    op.drop_index(op.f('ix_payment_recall_requests_deleted_at'), table_name='payment_recall_requests')
    op.alter_column('payment_recall_requests', 'processed_at',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.VARCHAR(length=30),
               existing_nullable=True)
    op.drop_index(op.f('ix_other_references_reference_id'), table_name='other_references')
    op.drop_index(op.f('ix_other_references_deleted_at'), table_name='other_references')
    op.drop_index(op.f('ix_modules_deleted_at'), table_name='modules')
    op.drop_constraint(None, 'lead_followups', type_='foreignkey')
    op.drop_index(op.f('ix_lead_followups_deleted_at'), table_name='lead_followups')
    op.drop_index(op.f('ix_invoices_deleted_at'), table_name='invoices')
    op.alter_column('invoices', 'balance_due',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=sa.REAL(),
               existing_nullable=False)
    op.alter_column('invoices', 'paid_amount',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=sa.REAL(),
               existing_nullable=False)
    op.alter_column('invoices', 'amount',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=sa.REAL(),
               existing_nullable=False)
    op.drop_index(op.f('ix_invoice_status_history_deleted_at'), table_name='invoice_status_history')
    op.drop_index(op.f('ix_invoice_status_history_changed_by'), table_name='invoice_status_history')
    op.drop_index(op.f('ix_invoice_line_items_fee_head_id'), table_name='invoice_line_items')
    op.drop_index(op.f('ix_invoice_line_items_deleted_at'), table_name='invoice_line_items')
    op.alter_column('invoice_line_items', 'net_amount',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=sa.REAL(),
               existing_nullable=False)
    op.alter_column('invoice_line_items', 'tax_amount',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('invoice_line_items', 'discount_amount',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('invoice_line_items', 'amount',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=sa.REAL(),
               existing_nullable=False)
    op.drop_index(op.f('ix_institutions_deleted_at'), table_name='institutions')
    op.drop_index(op.f('ix_hsc_details_deleted_at'), table_name='hsc_details')
    op.alter_column('hsc_details', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('hsc_details', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.drop_index(op.f('ix_hostels_deleted_at'), table_name='hostels')
    op.drop_index(op.f('ix_hostel_rooms_deleted_at'), table_name='hostel_rooms')
    op.add_column('hostel_fee_structures', sa.Column('college_id', sa.UUID(), autoincrement=False, nullable=True))
    op.execute("UPDATE hostel_fee_structures SET college_id = institution_id")
    op.alter_column('hostel_fee_structures', 'college_id', nullable=False)
    op.drop_constraint(None, 'hostel_fee_structures', type_='foreignkey')
    op.create_foreign_key(op.f('hostel_fee_structures_college_id_fkey'), 'hostel_fee_structures', 'institutions', ['college_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_hostel_fee_structures_institution_id'), table_name='hostel_fee_structures')
    op.drop_index(op.f('ix_hostel_fee_structures_deleted_at'), table_name='hostel_fee_structures')
    op.create_index(op.f('ix_hostel_fee_structures_college_id'), 'hostel_fee_structures', ['college_id'], unique=False)
    op.drop_column('hostel_fee_structures', 'institution_id')
    op.drop_constraint('uq_institution_financial_year_name', 'financial_years', type_='unique')
    op.drop_index(op.f('ix_financial_years_deleted_at'), table_name='financial_years')
    op.drop_index(op.f('ix_fee_sub_heads_deleted_at'), table_name='fee_sub_heads')
    op.drop_index(op.f('ix_fee_structures_deleted_at'), table_name='fee_structures')
    op.drop_index(op.f('ix_fee_structure_items_deleted_at'), table_name='fee_structure_items')
    op.drop_index(op.f('ix_fee_heads_institution_id'), table_name='fee_heads')
    op.drop_index(op.f('ix_fee_heads_deleted_at'), table_name='fee_heads')
    op.drop_index(op.f('ix_document_types_deleted_at'), table_name='document_types')
    op.alter_column('document_types', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('document_types', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_index(op.f('ix_diploma_details_deleted_at'), table_name='diploma_details')
    op.alter_column('diploma_details', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('diploma_details', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.drop_index(op.f('ix_departments_institution_id'), table_name='departments')
    op.drop_index(op.f('ix_departments_deleted_at'), table_name='departments')
    op.drop_constraint(None, 'department_change_requests', type_='foreignkey')
    op.drop_constraint(None, 'department_change_requests', type_='foreignkey')
    op.drop_index(op.f('ix_department_change_requests_reviewed_by'), table_name='department_change_requests')
    op.drop_index(op.f('ix_department_change_requests_requested_department_id'), table_name='department_change_requests')
    op.drop_index(op.f('ix_department_change_requests_requested_by'), table_name='department_change_requests')
    op.drop_index(op.f('ix_department_change_requests_deleted_at'), table_name='department_change_requests')
    op.drop_index(op.f('ix_department_change_requests_current_department_id'), table_name='department_change_requests')
    op.alter_column('department_change_requests', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('department_change_requests', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.drop_index(op.f('ix_demand_items_fee_head_id'), table_name='demand_items')
    op.drop_index(op.f('ix_demand_items_deleted_at'), table_name='demand_items')
    op.drop_index(op.f('ix_demand_batches_deleted_at'), table_name='demand_batches')
    op.drop_index(op.f('ix_courses_department_id'), table_name='courses')
    op.drop_index(op.f('ix_courses_deleted_at'), table_name='courses')
    op.drop_index(op.f('ix_consultancy_references_deleted_at'), table_name='consultancy_references')
    op.drop_index(op.f('ix_consultancy_references_consultancy_id'), table_name='consultancy_references')
    op.drop_index(op.f('ix_consultancies_deleted_at'), table_name='consultancies')
    op.add_column('concessions', sa.Column('college_id', sa.UUID(), autoincrement=False, nullable=True))
    op.execute("UPDATE concessions SET college_id = institution_id")
    op.alter_column('concessions', 'college_id', nullable=False)
    op.drop_constraint(None, 'concessions', type_='foreignkey')
    op.create_foreign_key(op.f('concessions_college_id_fkey'), 'concessions', 'institutions', ['college_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_concessions_institution_id'), table_name='concessions')
    op.drop_index(op.f('ix_concessions_deleted_at'), table_name='concessions')
    op.create_index(op.f('ix_concessions_college_id'), 'concessions', ['college_id'], unique=False)
    op.alter_column('concessions', 'end_date',
               existing_type=sa.Date(),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
    op.alter_column('concessions', 'start_date',
               existing_type=sa.Date(),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
    op.drop_column('concessions', 'institution_id')
    op.drop_index(op.f('ix_concession_audits_deleted_at'), table_name='concession_audits')
    op.drop_index(op.f('ix_communities_deleted_at'), table_name='communities')
    op.drop_index(op.f('ix_classes_deleted_at'), table_name='classes')
    op.drop_index(op.f('ix_classes_course_id'), table_name='classes')
    op.drop_index(op.f('ix_castes_deleted_at'), table_name='castes')
    op.drop_index(op.f('ix_castes_community_id'), table_name='castes')
    op.drop_constraint(None, 'cash_counters', type_='foreignkey')
    op.drop_index(op.f('ix_cash_counters_deleted_at'), table_name='cash_counters')
    op.drop_index(op.f('ix_application_transactions_deleted_at'), table_name='application_transactions')
    op.drop_index(op.f('ix_application_transactions_cash_counter_id'), table_name='application_transactions')
    op.alter_column('application_transactions', 'amount',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=sa.REAL(),
               existing_nullable=False)
    op.drop_index(op.f('ix_admission_visitors_institution_id'), table_name='admission_visitors')
    op.drop_index(op.f('ix_admission_visitors_deleted_at'), table_name='admission_visitors')
    op.create_index(op.f('ix_admission_visitors_visit_status'), 'admission_visitors', ['visit_status'], unique=False)
    op.create_index(op.f('ix_admission_visitors_check_out_time'), 'admission_visitors', ['check_out_time'], unique=False)
    op.create_index(op.f('ix_admission_visitors_check_in_time'), 'admission_visitors', ['check_in_time'], unique=False)
    op.alter_column('admission_visitors', 'visit_status',
               existing_type=sa.Enum('PENDING', 'CHECKED_IN', 'CHECKED_OUT', 'CANCELLED', name='visitstatus', native_enum=False),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False,
               existing_server_default=sa.text("'CHECKED_IN'::character varying"))
    op.drop_index(op.f('ix_admission_types_deleted_at'), table_name='admission_types')
    op.alter_column('admission_types', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('admission_types', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_admission_students_fee_structure_locked_by'), table_name='admission_students')
    op.drop_index(op.f('ix_admission_students_deleted_at'), table_name='admission_students')
    op.alter_column('admission_students', 'parent_income',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    op.drop_index(op.f('ix_admission_required_certificates_deleted_at'), table_name='admission_required_certificates')
    op.alter_column('admission_required_certificates', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('admission_required_certificates', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_constraint(None, 'admission_form_verifications', type_='foreignkey')
    op.drop_constraint(None, 'admission_form_verifications', type_='foreignkey')
    op.drop_constraint(None, 'admission_form_verifications', type_='foreignkey')
    op.drop_constraint(None, 'admission_form_verifications', type_='foreignkey')
    op.drop_index(op.f('ix_admission_form_verifications_provisionally_allotted_by'), table_name='admission_form_verifications')
    op.drop_index(op.f('ix_admission_form_verifications_form_printed_by'), table_name='admission_form_verifications')
    op.drop_index(op.f('ix_admission_form_verifications_deleted_at'), table_name='admission_form_verifications')
    op.drop_index(op.f('ix_admission_form_verifications_certificate_verified_by'), table_name='admission_form_verifications')
    op.drop_index(op.f('ix_admission_form_verifications_application_received_by'), table_name='admission_form_verifications')
    op.alter_column('admission_form_verifications', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('admission_form_verifications', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.drop_constraint('uq_institution_year_name', 'academic_years', type_='unique')
    op.drop_index(op.f('ix_academic_years_institution_id'), table_name='academic_years')
    op.drop_index(op.f('ix_academic_years_deleted_at'), table_name='academic_years')
    op.drop_constraint('uq_academic_year_course', 'academic_year_courses', type_='unique')
    op.drop_index(op.f('ix_academic_year_courses_deleted_at'), table_name='academic_year_courses')
    op.drop_index(op.f('ix_academic_year_courses_course_id'), table_name='academic_year_courses')
    op.drop_index(op.f('ix_academic_year_courses_academic_year_id'), table_name='academic_year_courses')
    op.alter_column('academic_year_courses', 'application_fee',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
    
    # --- Drop manually added CHECK constraints ---
    op.drop_constraint('ck_app_txn_amount_positive', 'application_transactions', type_='check')
    op.drop_constraint('ck_payment_amount_positive', 'payments', type_='check')
    op.drop_constraint('ck_line_item_net_non_negative', 'invoice_line_items', type_='check')
    op.drop_constraint('ck_line_item_amount_non_negative', 'invoice_line_items', type_='check')
    op.drop_constraint('ck_invoice_balance_non_negative', 'invoices', type_='check')
    op.drop_constraint('ck_invoice_paid_amount_non_negative', 'invoices', type_='check')
    op.drop_constraint('ck_invoice_amount_non_negative', 'invoices', type_='check')
    op.drop_constraint('ck_semester_period_dates', 'semester_periods', type_='check')
    op.drop_constraint('ck_application_fee_non_negative', 'academic_year_courses', type_='check')
    op.drop_constraint('ck_academic_year_dates', 'academic_years', type_='check')
    op.drop_constraint('ck_total_semesters_positive', 'courses', type_='check')
    op.drop_constraint('ck_course_duration_positive', 'courses', type_='check')
    # ### end Alembic commands ###
