"""add_cash_counter_and_payment_updates_v2

Revision ID: 95201cfe47d3
Revises: 9a5fd3cfc497
Create Date: 2026-01-15 07:56:39.410797

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '95201cfe47d3'
down_revision: Union[str, Sequence[str], None] = '9a5fd3cfc497'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cash_counters',
    sa.Column('institution_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('deleted_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], initially='DEFERRED', deferrable=True, use_alter=True),
    sa.ForeignKeyConstraint(['deleted_by'], ['users.id'], initially='DEFERRED', deferrable=True, use_alter=True),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], initially='DEFERRED', deferrable=True, use_alter=True),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cash_counters_code'), 'cash_counters', ['code'], unique=True)
    op.create_index(op.f('ix_cash_counters_institution_id'), 'cash_counters', ['institution_id'], unique=False)

    
    op.create_foreign_key(None, 'departments', 'institutions', ['institution_id'], ['id'])
    op.create_foreign_key(None, 'diploma_details', 'admission_students', ['student_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'hsc_details', 'admission_students', ['student_id'], ['id'], ondelete='CASCADE')
    
    op.alter_column('invoice_line_items', 'amount',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=2),
               existing_nullable=False)
    op.alter_column('invoice_line_items', 'discount_amount',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=2),
               existing_nullable=True)
    op.alter_column('invoice_line_items', 'tax_amount',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=2),
               existing_nullable=True)
    op.alter_column('invoice_line_items', 'net_amount',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=2),
               existing_nullable=False)
    op.create_foreign_key(None, 'invoice_line_items', 'fee_heads', ['fee_head_id'], ['id'], ondelete='SET NULL')
    
    op.alter_column('invoices', 'amount',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=2),
               existing_nullable=False)
    op.alter_column('invoices', 'paid_amount',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=2),
               existing_nullable=False)
    op.alter_column('invoices', 'balance_due',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=2),
               existing_nullable=False)
    op.create_foreign_key(None, 'invoices', 'admission_students', ['student_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'invoices', 'institutions', ['institution_id'], ['id'], ondelete='CASCADE')
    
    op.add_column('payments', sa.Column('cash_counter_id', sa.UUID(), nullable=True))
    op.alter_column('payments', 'amount',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=2),
               existing_nullable=False)
    op.create_foreign_key(None, 'payments', 'cash_counters', ['cash_counter_id'], ['id'], ondelete='SET NULL')
    
    op.create_foreign_key(None, 'pg_details', 'admission_students', ['student_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'sslc_details', 'admission_students', ['student_id'], ['id'], ondelete='CASCADE')
    
    op.add_column('visitors', sa.Column('pass_number', sa.String(length=50), nullable=True))
    op.drop_index('ix_visitors_gate_pass_no', table_name='visitors')
    op.drop_constraint('uq_visitors_gate_pass_no', 'visitors', type_='unique')
    op.create_unique_constraint(None, 'visitors', ['pass_number'])
    op.create_foreign_key(None, 'visitors', 'institutions', ['institution_id'], ['id'])
    op.drop_column('visitors', 'gate_pass_no')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('visitors', sa.Column('gate_pass_no', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'visitors', type_='foreignkey')
    op.drop_constraint(None, 'visitors', type_='unique')
    op.create_unique_constraint('uq_visitors_gate_pass_no', 'visitors', ['gate_pass_no'])
    op.create_index('ix_visitors_gate_pass_no', 'visitors', ['gate_pass_no'], unique=False)
    op.drop_column('visitors', 'pass_number')
    
    op.drop_constraint(None, 'sslc_details', type_='foreignkey')
    op.drop_constraint(None, 'pg_details', type_='foreignkey')
    
    op.drop_constraint(None, 'payments', type_='foreignkey')
    op.alter_column('payments', 'amount',
               existing_type=sa.Float(precision=2),
               type_=sa.REAL(),
               existing_nullable=False)
    op.drop_column('payments', 'cash_counter_id')
    
    op.drop_constraint(None, 'invoices', type_='foreignkey')
    op.drop_constraint(None, 'invoices', type_='foreignkey')
    op.alter_column('invoices', 'balance_due',
               existing_type=sa.Float(precision=2),
               type_=sa.REAL(),
               existing_nullable=False)
    op.alter_column('invoices', 'paid_amount',
               existing_type=sa.Float(precision=2),
               type_=sa.REAL(),
               existing_nullable=False)
    op.alter_column('invoices', 'amount',
               existing_type=sa.Float(precision=2),
               type_=sa.REAL(),
               existing_nullable=False)
    
    op.drop_constraint(None, 'invoice_line_items', type_='foreignkey')
    op.alter_column('invoice_line_items', 'net_amount',
               existing_type=sa.Float(precision=2),
               type_=sa.REAL(),
               existing_nullable=False)
    op.alter_column('invoice_line_items', 'tax_amount',
               existing_type=sa.Float(precision=2),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('invoice_line_items', 'discount_amount',
               existing_type=sa.Float(precision=2),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('invoice_line_items', 'amount',
               existing_type=sa.Float(precision=2),
               type_=sa.REAL(),
               existing_nullable=False)
    
    op.drop_constraint(None, 'hsc_details', type_='foreignkey')
    op.drop_constraint(None, 'diploma_details', type_='foreignkey')
    op.drop_constraint(None, 'departments', type_='foreignkey')
    
    op.drop_index(op.f('ix_cash_counters_institution_id'), table_name='cash_counters')
    op.drop_index(op.f('ix_cash_counters_code'), table_name='cash_counters')
    op.drop_table('cash_counters')
    # ### end Alembic commands ###
