"""Add certificate verification workflow

Revision ID: bb7103d7b9e6
Revises: 8b57af46c7a1
Create Date: 2026-02-14 14:45:03.110751

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bb7103d7b9e6'
down_revision: Union[str, Sequence[str], None] = '8b57af46c7a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admission_form_verifications', sa.Column('application_received', sa.Boolean(), nullable=False))
    op.add_column('admission_form_verifications', sa.Column('application_received_at', sa.DateTime(), nullable=True))
    op.add_column('admission_form_verifications', sa.Column('application_received_by', sa.UUID(), nullable=True))
    op.add_column('admission_form_verifications', sa.Column('provisionally_allotted', sa.Boolean(), nullable=False))
    op.add_column('admission_form_verifications', sa.Column('provisionally_allotted_at', sa.DateTime(), nullable=True))
    op.add_column('admission_form_verifications', sa.Column('provisionally_allotted_by', sa.UUID(), nullable=True))
    op.alter_column('admission_visitors', 'status',
               existing_type=sa.VARCHAR(length=18),
               type_=sa.Enum('ENQUIRY', 'APPLIED', 'DOCUMENTS_PENDING', 'DOCUMENTS_VERIFIED', 'FEE_PENDING', 'FEE_RECEIVED', 'ADMISSION_GRANTED', 'FORM_VERIFICATION_PENDING', 'FORM_VERIFIED', 'APPLICATION_RECEIVED', 'PROVISIONALLY_ALLOTTED', 'ENROLLED', 'WAITLISTED', 'REJECTED', 'WITHDRAWN', 'ON_HOLD', name='admissionstatusenum', native_enum=False),
               existing_nullable=False,
               existing_server_default=sa.text("'APPLIED'::character varying"))
    op.alter_column('application_transactions', 'amount',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=2),
               existing_nullable=False)
    op.alter_column('invoice_line_items', 'amount',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=2),
               existing_nullable=False)
    op.alter_column('invoice_line_items', 'discount_amount',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=2),
               existing_nullable=True)
    op.alter_column('invoice_line_items', 'tax_amount',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=2),
               existing_nullable=True)
    op.alter_column('invoice_line_items', 'net_amount',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=2),
               existing_nullable=False)
    op.alter_column('invoices', 'amount',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=2),
               existing_nullable=False)
    op.alter_column('invoices', 'paid_amount',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=2),
               existing_nullable=False)
    op.alter_column('invoices', 'balance_due',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=2),
               existing_nullable=False)
    op.alter_column('payments', 'amount',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=2),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('payments', 'amount',
               existing_type=sa.Float(precision=2),
               type_=sa.REAL(),
               existing_nullable=False)
    op.alter_column('invoices', 'balance_due',
               existing_type=sa.Float(precision=2),
               type_=sa.REAL(),
               existing_nullable=False)
    op.alter_column('invoices', 'paid_amount',
               existing_type=sa.Float(precision=2),
               type_=sa.REAL(),
               existing_nullable=False)
    op.alter_column('invoices', 'amount',
               existing_type=sa.Float(precision=2),
               type_=sa.REAL(),
               existing_nullable=False)
    op.alter_column('invoice_line_items', 'net_amount',
               existing_type=sa.Float(precision=2),
               type_=sa.REAL(),
               existing_nullable=False)
    op.alter_column('invoice_line_items', 'tax_amount',
               existing_type=sa.Float(precision=2),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('invoice_line_items', 'discount_amount',
               existing_type=sa.Float(precision=2),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('invoice_line_items', 'amount',
               existing_type=sa.Float(precision=2),
               type_=sa.REAL(),
               existing_nullable=False)
    op.alter_column('application_transactions', 'amount',
               existing_type=sa.Float(precision=2),
               type_=sa.REAL(),
               existing_nullable=False)
    op.alter_column('admission_visitors', 'status',
               existing_type=sa.Enum('ENQUIRY', 'APPLIED', 'DOCUMENTS_PENDING', 'DOCUMENTS_VERIFIED', 'FEE_PENDING', 'FEE_RECEIVED', 'ADMISSION_GRANTED', 'FORM_VERIFICATION_PENDING', 'FORM_VERIFIED', 'APPLICATION_RECEIVED', 'PROVISIONALLY_ALLOTTED', 'ENROLLED', 'WAITLISTED', 'REJECTED', 'WITHDRAWN', 'ON_HOLD', name='admissionstatusenum', native_enum=False),
               type_=sa.VARCHAR(length=18),
               existing_nullable=False,
               existing_server_default=sa.text("'APPLIED'::character varying"))
    op.drop_column('admission_form_verifications', 'provisionally_allotted_by')
    op.drop_column('admission_form_verifications', 'provisionally_allotted_at')
    op.drop_column('admission_form_verifications', 'provisionally_allotted')
    op.drop_column('admission_form_verifications', 'application_received_by')
    op.drop_column('admission_form_verifications', 'application_received_at')
    op.drop_column('admission_form_verifications', 'application_received')
    # ### end Alembic commands ###
