"""remove legacy admission fields

Revision ID: e79fe14af403
Revises: 20260404_adm_split
Create Date: 2026-04-05 04:09:37.462748

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e79fe14af403'
down_revision: Union[str, Sequence[str], None] = '20260404_adm_split'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('admission_students_aadhaar_number_key'), 'admission_students', type_='unique')
    op.drop_index(op.f('ix_admission_students_course_id'), table_name='admission_students')
    op.drop_index(op.f('ix_admission_students_department_id'), table_name='admission_students')
    op.drop_index(op.f('ix_admission_students_gate_pass_number'), table_name='admission_students')
    op.drop_index(op.f('ix_admission_students_institution_id'), table_name='admission_students')
    op.drop_index(op.f('ix_admission_students_name'), table_name='admission_students')
    op.drop_constraint(op.f('admission_students_course_id_fkey'), 'admission_students', type_='foreignkey')
    op.drop_constraint(op.f('admission_students_institution_id_fkey'), 'admission_students', type_='foreignkey')
    op.drop_constraint(op.f('admission_students_department_id_fkey'), 'admission_students', type_='foreignkey')
    op.drop_column('admission_students', 'door_no')
    op.drop_column('admission_students', 'district')
    op.drop_column('admission_students', 'state')
    op.drop_column('admission_students', 'campus')
    op.drop_column('admission_students', 'permanent_address')
    op.drop_column('admission_students', 'community')
    op.drop_column('admission_students', 'caste')
    op.drop_column('admission_students', 'village_name')
    op.drop_column('admission_students', 'department_id')
    op.drop_column('admission_students', 'source')
    op.drop_column('admission_students', 'check_out_time')
    op.drop_column('admission_students', 'check_in_time')
    op.drop_column('admission_students', 'check_out_remarks')
    op.drop_column('admission_students', 'vehicle_number')
    op.drop_column('admission_students', 'is_lateral_entry')
    op.drop_column('admission_students', 'aadhaar_number')
    op.drop_column('admission_students', 'institution_id')
    op.drop_column('admission_students', 'parent_mobile')
    op.drop_column('admission_students', 'gate_pass_number')
    op.drop_column('admission_students', 'taluk')
    op.drop_column('admission_students', 'has_vehicle')
    op.drop_column('admission_students', 'year')
    op.drop_column('admission_students', 'native_place')
    op.drop_column('admission_students', 'date_of_birth')
    op.drop_column('admission_students', 'course_id')
    op.drop_column('admission_students', 'religion')
    op.drop_column('admission_students', 'street_name')
    op.drop_column('admission_students', 'branch')
    op.drop_column('admission_students', 'pincode')
    op.drop_column('admission_students', 'father_name')
    op.drop_column('admission_students', 'name')
    op.drop_column('admission_students', 'parent_income')
    op.drop_column('admission_students', 'parent_address')
    op.drop_column('admission_students', 'image_url')
    op.drop_column('admission_students', 'visit_status')
    op.drop_column('admission_students', 'previous_academic_level')
    op.drop_column('admission_students', 'student_mobile')
    op.drop_column('admission_students', 'reference_type')
    op.drop_column('admission_students', 'gender')
    op.drop_index(op.f('ix_multi_receipt_items_created_at'), table_name='multi_receipt_items')
    op.drop_index(op.f('ix_multi_receipt_items_id'), table_name='multi_receipt_items')
    op.drop_index(op.f('ix_multi_receipt_items_updated_at'), table_name='multi_receipt_items')
    op.drop_index(op.f('ix_multi_receipts_created_at'), table_name='multi_receipts')
    op.drop_index(op.f('ix_multi_receipts_id'), table_name='multi_receipts')
    op.drop_index(op.f('ix_multi_receipts_updated_at'), table_name='multi_receipts')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_multi_receipts_updated_at'), 'multi_receipts', ['updated_at'], unique=False)
    op.create_index(op.f('ix_multi_receipts_id'), 'multi_receipts', ['id'], unique=False)
    op.create_index(op.f('ix_multi_receipts_created_at'), 'multi_receipts', ['created_at'], unique=False)
    op.create_index(op.f('ix_multi_receipt_items_updated_at'), 'multi_receipt_items', ['updated_at'], unique=False)
    op.create_index(op.f('ix_multi_receipt_items_id'), 'multi_receipt_items', ['id'], unique=False)
    op.create_index(op.f('ix_multi_receipt_items_created_at'), 'multi_receipt_items', ['created_at'], unique=False)
    op.add_column('admission_students', sa.Column('gender', postgresql.ENUM('MALE', 'FEMALE', 'OTHER', name='genderenum'), autoincrement=False, nullable=True))
    op.add_column('admission_students', sa.Column('reference_type', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('admission_students', sa.Column('student_mobile', sa.VARCHAR(length=15), autoincrement=False, nullable=True))
    op.add_column('admission_students', sa.Column('previous_academic_level', postgresql.ENUM('TENTH', 'TWELFTH', 'DIPLOMA', 'DEGREE', name='previousacademiclevelenum'), autoincrement=False, nullable=True))
    op.add_column('admission_students', sa.Column('visit_status', postgresql.ENUM('PENDING', 'CHECKED_IN', 'CHECKED_OUT', 'CANCELLED', name='visitstatusenum'), autoincrement=False, nullable=True))
    op.add_column('admission_students', sa.Column('image_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.add_column('admission_students', sa.Column('parent_address', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('admission_students', sa.Column('parent_income', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=True))
    op.add_column('admission_students', sa.Column('name', sa.VARCHAR(length=200), autoincrement=False, nullable=False))
    op.add_column('admission_students', sa.Column('father_name', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    op.add_column('admission_students', sa.Column('pincode', sa.VARCHAR(length=10), autoincrement=False, nullable=True))
    op.add_column('admission_students', sa.Column('branch', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    op.add_column('admission_students', sa.Column('street_name', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    op.add_column('admission_students', sa.Column('religion', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('admission_students', sa.Column('course_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('admission_students', sa.Column('date_of_birth', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('admission_students', sa.Column('native_place', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('admission_students', sa.Column('year', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('admission_students', sa.Column('has_vehicle', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('admission_students', sa.Column('taluk', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('admission_students', sa.Column('gate_pass_number', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('admission_students', sa.Column('parent_mobile', sa.VARCHAR(length=15), autoincrement=False, nullable=True))
    op.add_column('admission_students', sa.Column('institution_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('admission_students', sa.Column('aadhaar_number', sa.VARCHAR(length=12), autoincrement=False, nullable=True))
    op.add_column('admission_students', sa.Column('is_lateral_entry', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.add_column('admission_students', sa.Column('vehicle_number', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('admission_students', sa.Column('check_out_remarks', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('admission_students', sa.Column('check_in_time', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('admission_students', sa.Column('check_out_time', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('admission_students', sa.Column('source', postgresql.ENUM('GATE_ENQUIRY', 'DIRECT_ENTRY', 'COUNSELING', name='sourceenum'), autoincrement=False, nullable=False))
    op.add_column('admission_students', sa.Column('department_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('admission_students', sa.Column('village_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('admission_students', sa.Column('caste', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('admission_students', sa.Column('community', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('admission_students', sa.Column('permanent_address', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('admission_students', sa.Column('campus', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    op.add_column('admission_students', sa.Column('state', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('admission_students', sa.Column('district', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('admission_students', sa.Column('door_no', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('admission_students_department_id_fkey'), 'admission_students', 'departments', ['department_id'], ['id'])
    op.create_foreign_key(op.f('admission_students_institution_id_fkey'), 'admission_students', 'institutions', ['institution_id'], ['id'])
    op.create_foreign_key(op.f('admission_students_course_id_fkey'), 'admission_students', 'courses', ['course_id'], ['id'])
    op.create_index(op.f('ix_admission_students_name'), 'admission_students', ['name'], unique=False)
    op.create_index(op.f('ix_admission_students_institution_id'), 'admission_students', ['institution_id'], unique=False)
    op.create_index(op.f('ix_admission_students_gate_pass_number'), 'admission_students', ['gate_pass_number'], unique=True)
    op.create_index(op.f('ix_admission_students_department_id'), 'admission_students', ['department_id'], unique=False)
    op.create_index(op.f('ix_admission_students_course_id'), 'admission_students', ['course_id'], unique=False)
    op.create_unique_constraint(op.f('admission_students_aadhaar_number_key'), 'admission_students', ['aadhaar_number'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
