"""add_staff_table_update_references

Revision ID: e943424e905a
Revises: 7dd775a7e0b2
Create Date: 2026-02-26 07:40:12.314784

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e943424e905a'
down_revision: Union[str, Sequence[str], None] = '7dd775a7e0b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('consultancy_references', 'contact_number')
    # add staff_id as nullable to avoid failing on existing rows without a value
    op.add_column('staff_references', sa.Column('staff_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_staff_references_staff_id'), 'staff_references', ['staff_id'], unique=False)
    op.create_foreign_key(None, 'staff_references', 'staff_members', ['staff_id'], ['id'])
    op.drop_column('staff_references', 'department')
    op.drop_column('staff_references', 'staff_name')
    op.drop_column('staff_references', 'contact_number')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('staff_references', sa.Column('contact_number', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    op.add_column('staff_references', sa.Column('staff_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('staff_references', sa.Column('department', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'staff_references', type_='foreignkey')
    op.drop_index(op.f('ix_staff_references_staff_id'), table_name='staff_references')
    op.drop_column('staff_references', 'staff_id')
    op.add_column('consultancy_references', sa.Column('contact_number', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
