"""refactor_app_fee_to_course

Revision ID: f18b4d43ac77
Revises: f10f0a9416c9
Create Date: 2026-01-28 03:36:34.792868

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f18b4d43ac77'
down_revision: Union[str, Sequence[str], None] = 'f10f0a9416c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_academic_year_departments_academic_year_id'), table_name='academic_year_departments')
    op.drop_index(op.f('ix_academic_year_departments_department_id'), table_name='academic_year_departments')
    op.drop_table('academic_year_departments')
    op.add_column('application_transactions', sa.Column('course_id', sa.UUID(), nullable=False))
    op.alter_column('application_transactions', 'amount',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=2),
               existing_nullable=False)
    op.drop_index(op.f('ix_application_transactions_department_id'), table_name='application_transactions')
    op.create_index(op.f('ix_application_transactions_course_id'), 'application_transactions', ['course_id'], unique=False)
    op.drop_constraint(op.f('application_transactions_department_id_fkey'), 'application_transactions', type_='foreignkey')
    op.create_foreign_key(None, 'application_transactions', 'courses', ['course_id'], ['id'], ondelete='CASCADE')
    op.drop_column('application_transactions', 'department_id')
    op.drop_index(op.f('ix_fee_structures_active'), table_name='fee_structures')
    op.drop_column('fee_structures', 'active')
    op.alter_column('invoice_line_items', 'amount',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=2),
               existing_nullable=False)
    op.alter_column('invoice_line_items', 'discount_amount',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=2),
               existing_nullable=True)
    op.alter_column('invoice_line_items', 'tax_amount',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=2),
               existing_nullable=True)
    op.alter_column('invoice_line_items', 'net_amount',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=2),
               existing_nullable=False)
    op.alter_column('invoices', 'amount',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=2),
               existing_nullable=False)
    op.alter_column('invoices', 'paid_amount',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=2),
               existing_nullable=False)
    op.alter_column('invoices', 'balance_due',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=2),
               existing_nullable=False)
    op.alter_column('payments', 'amount',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=2),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('payments', 'amount',
               existing_type=sa.Float(precision=2),
               type_=sa.REAL(),
               existing_nullable=False)
    op.alter_column('invoices', 'balance_due',
               existing_type=sa.Float(precision=2),
               type_=sa.REAL(),
               existing_nullable=False)
    op.alter_column('invoices', 'paid_amount',
               existing_type=sa.Float(precision=2),
               type_=sa.REAL(),
               existing_nullable=False)
    op.alter_column('invoices', 'amount',
               existing_type=sa.Float(precision=2),
               type_=sa.REAL(),
               existing_nullable=False)
    op.alter_column('invoice_line_items', 'net_amount',
               existing_type=sa.Float(precision=2),
               type_=sa.REAL(),
               existing_nullable=False)
    op.alter_column('invoice_line_items', 'tax_amount',
               existing_type=sa.Float(precision=2),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('invoice_line_items', 'discount_amount',
               existing_type=sa.Float(precision=2),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('invoice_line_items', 'amount',
               existing_type=sa.Float(precision=2),
               type_=sa.REAL(),
               existing_nullable=False)
    op.add_column('fee_structures', sa.Column('active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False))
    op.create_index(op.f('ix_fee_structures_active'), 'fee_structures', ['active'], unique=False)
    op.add_column('application_transactions', sa.Column('department_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'application_transactions', type_='foreignkey')
    op.create_foreign_key(op.f('application_transactions_department_id_fkey'), 'application_transactions', 'departments', ['department_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_application_transactions_course_id'), table_name='application_transactions')
    op.create_index(op.f('ix_application_transactions_department_id'), 'application_transactions', ['department_id'], unique=False)
    op.alter_column('application_transactions', 'amount',
               existing_type=sa.Float(precision=2),
               type_=sa.REAL(),
               existing_nullable=False)
    op.drop_column('application_transactions', 'course_id')
    op.create_table('academic_year_departments',
    sa.Column('academic_year_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('department_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('application_fee', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text("'0'::double precision"), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('deleted_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['academic_year_id'], ['academic_years.id'], name=op.f('academic_year_departments_academic_year_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('academic_year_departments_created_by_fkey'), initially='DEFERRED', deferrable=True),
    sa.ForeignKeyConstraint(['deleted_by'], ['users.id'], name=op.f('academic_year_departments_deleted_by_fkey'), initially='DEFERRED', deferrable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], name=op.f('academic_year_departments_department_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f('academic_year_departments_updated_by_fkey'), initially='DEFERRED', deferrable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('academic_year_departments_pkey'))
    )
    op.create_index(op.f('ix_academic_year_departments_department_id'), 'academic_year_departments', ['department_id'], unique=False)
    op.create_index(op.f('ix_academic_year_departments_academic_year_id'), 'academic_year_departments', ['academic_year_id'], unique=False)
    # ### end Alembic commands ###
