"""

Revision ID: f829991d211e
Revises: 74b1679ceb92
Create Date: 2026-01-19 11:03:24.762813

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f829991d211e'
down_revision: Union[str, Sequence[str], None] = '74b1679ceb92'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payment_recall_requests_payment_id'), table_name='payment_recall_requests')
    op.drop_table('payment_recall_requests')
    op.alter_column('application_transactions', 'amount',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=2),
               existing_nullable=False)
    op.drop_index(op.f('ix_fee_sub_heads_batch'), table_name='fee_sub_heads')
    op.drop_column('fee_sub_heads', 'batch')
    op.add_column('hostels', sa.Column('name', sa.String(length=200), nullable=False))
    op.add_column('hostels', sa.Column('institution_id', sa.UUID(), nullable=False))
    op.add_column('hostels', sa.Column('code', sa.String(length=50), nullable=True))
    op.add_column('hostels', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.add_column('hostels', sa.Column('meta', sa.JSON(), nullable=True))
    op.drop_index(op.f('ix_hostels_college_id'), table_name='hostels')
    op.drop_index(op.f('ix_hostels_hostel_category'), table_name='hostels')
    op.drop_index(op.f('ix_hostels_hostel_code'), table_name='hostels')
    op.drop_index(op.f('ix_hostels_hostel_name'), table_name='hostels')
    op.drop_index(op.f('ix_hostels_hostel_status'), table_name='hostels')
    op.drop_index(op.f('ix_hostels_hostel_type'), table_name='hostels')
    op.create_index(op.f('ix_hostels_code'), 'hostels', ['code'], unique=False)
    op.create_index(op.f('ix_hostels_institution_id'), 'hostels', ['institution_id'], unique=False)
    op.drop_constraint(op.f('hostels_college_id_fkey'), 'hostels', type_='foreignkey')
    op.create_foreign_key(None, 'hostels', 'institutions', ['institution_id'], ['id'], ondelete='CASCADE')
    op.drop_column('hostels', 'hostel_code')
    op.drop_column('hostels', 'college_id')
    op.drop_column('hostels', 'hostel_type')
    op.drop_column('hostels', 'hostel_meta')
    op.drop_column('hostels', 'hostel_description')
    op.drop_column('hostels', 'hostel_status')
    op.drop_column('hostels', 'hostel_name')
    op.drop_column('hostels', 'hostel_category')
    op.alter_column('invoice_line_items', 'amount',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=2),
               existing_nullable=False)
    op.alter_column('invoice_line_items', 'discount_amount',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=2),
               existing_nullable=True)
    op.alter_column('invoice_line_items', 'tax_amount',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=2),
               existing_nullable=True)
    op.alter_column('invoice_line_items', 'net_amount',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=2),
               existing_nullable=False)
    op.alter_column('invoices', 'amount',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=2),
               existing_nullable=False)
    op.alter_column('invoices', 'paid_amount',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=2),
               existing_nullable=False)
    op.alter_column('invoices', 'balance_due',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=2),
               existing_nullable=False)
    op.alter_column('payments', 'amount',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=2),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('payments', 'amount',
               existing_type=sa.Float(precision=2),
               type_=sa.REAL(),
               existing_nullable=False)
    op.alter_column('invoices', 'balance_due',
               existing_type=sa.Float(precision=2),
               type_=sa.REAL(),
               existing_nullable=False)
    op.alter_column('invoices', 'paid_amount',
               existing_type=sa.Float(precision=2),
               type_=sa.REAL(),
               existing_nullable=False)
    op.alter_column('invoices', 'amount',
               existing_type=sa.Float(precision=2),
               type_=sa.REAL(),
               existing_nullable=False)
    op.alter_column('invoice_line_items', 'net_amount',
               existing_type=sa.Float(precision=2),
               type_=sa.REAL(),
               existing_nullable=False)
    op.alter_column('invoice_line_items', 'tax_amount',
               existing_type=sa.Float(precision=2),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('invoice_line_items', 'discount_amount',
               existing_type=sa.Float(precision=2),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('invoice_line_items', 'amount',
               existing_type=sa.Float(precision=2),
               type_=sa.REAL(),
               existing_nullable=False)
    op.add_column('hostels', sa.Column('hostel_category', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.add_column('hostels', sa.Column('hostel_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.add_column('hostels', sa.Column('hostel_status', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.add_column('hostels', sa.Column('hostel_description', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.add_column('hostels', sa.Column('hostel_meta', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('hostels', sa.Column('hostel_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.add_column('hostels', sa.Column('college_id', sa.UUID(), autoincrement=False, nullable=False))
    op.add_column('hostels', sa.Column('hostel_code', sa.VARCHAR(length=10), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'hostels', type_='foreignkey')
    op.create_foreign_key(op.f('hostels_college_id_fkey'), 'hostels', 'institutions', ['college_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_hostels_institution_id'), table_name='hostels')
    op.drop_index(op.f('ix_hostels_code'), table_name='hostels')
    op.create_index(op.f('ix_hostels_hostel_type'), 'hostels', ['hostel_type'], unique=False)
    op.create_index(op.f('ix_hostels_hostel_status'), 'hostels', ['hostel_status'], unique=False)
    op.create_index(op.f('ix_hostels_hostel_name'), 'hostels', ['hostel_name'], unique=False)
    op.create_index(op.f('ix_hostels_hostel_code'), 'hostels', ['hostel_code'], unique=False)
    op.create_index(op.f('ix_hostels_hostel_category'), 'hostels', ['hostel_category'], unique=False)
    op.create_index(op.f('ix_hostels_college_id'), 'hostels', ['college_id'], unique=False)
    op.drop_column('hostels', 'meta')
    op.drop_column('hostels', 'is_active')
    op.drop_column('hostels', 'code')
    op.drop_column('hostels', 'institution_id')
    op.drop_column('hostels', 'name')
    op.add_column('fee_sub_heads', sa.Column('batch', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_fee_sub_heads_batch'), 'fee_sub_heads', ['batch'], unique=False)
    op.alter_column('application_transactions', 'amount',
               existing_type=sa.Float(precision=2),
               type_=sa.REAL(),
               existing_nullable=False)
    op.create_table('payment_recall_requests',
    sa.Column('payment_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('requested_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('reason', sa.VARCHAR(length=1000), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('processed_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('processed_at', sa.VARCHAR(length=30), autoincrement=False, nullable=True),
    sa.Column('meta', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('deleted_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('payment_recall_requests_created_by_fkey'), initially='DEFERRED', deferrable=True),
    sa.ForeignKeyConstraint(['deleted_by'], ['users.id'], name=op.f('payment_recall_requests_deleted_by_fkey'), initially='DEFERRED', deferrable=True),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], name=op.f('payment_recall_requests_payment_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['processed_by'], ['users.id'], name=op.f('payment_recall_requests_processed_by_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['requested_by'], ['users.id'], name=op.f('payment_recall_requests_requested_by_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f('payment_recall_requests_updated_by_fkey'), initially='DEFERRED', deferrable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('payment_recall_requests_pkey'))
    )
    op.create_index(op.f('ix_payment_recall_requests_payment_id'), 'payment_recall_requests', ['payment_id'], unique=False)
    # ### end Alembic commands ###
